<Workspace Version="0.7.0.21043" X="-1264.80912306583" Y="-664.627318313002" zoom="1.26559229607736" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="357e7a53-361c-4c1e-81ae-83e16213a39a" nickname="AdaptiveComponent.ByPoints" x="1980.4362095" y="939.652260595424" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\RevitNodes.dll" function="Revit.Elements.AdaptiveComponent.ByPoints@Autodesk.DesignScript.Geometry.Point[],Revit.Elements.FamilySymbol" />
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="eed8d389-5ad2-4ac0-a270-7d737f487ad0" nickname="Select Model Element" x="846.35713721073" y="813.096583627717" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="f46e385f-3b0a-446c-adeb-8d419a480cba" nickname="Select Model Element" x="846.35713721073" y="671.368151070194" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="fe4c569f-a1b4-46da-8e76-d1b1bd5b6ef4" nickname="Select Model Element" x="846.35713721073" y="954.82501618524" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="83f06d4b-59ed-4888-a259-43d12f3d1736" nickname="Curve.PointAtParameter" x="1499.1553726301" y="843.496460893599" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double" />
    <DSCoreNodesUI.CreateList type="DSCoreNodesUI.CreateList" guid="765c3e25-1262-4f2b-ab25-08ece79508f5" nickname="Create List" x="1093.97818501915" y="777.087284360294" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="3" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="ddaba609-2fa0-4d18-be64-1443ad3d08f1" nickname="Code Block" x="1222" y="1047" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..1..#x;" ShouldFocus="false" />
    <Dynamo.Nodes.IntegerSlider type="Dynamo.Nodes.IntegerSlider" guid="cc3ba87a-cc1f-4db6-99f2-769f3020e0df" nickname="Integer Slider" x="836.432595609163" y="1114.41035310441" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Int32>5</System.Int32>
      <Range min="2" max="10" />
    </Dynamo.Nodes.IntegerSlider>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="13ca5899-91cd-448b-b475-a286eb0fbfba" nickname="Transpose" x="1733.2451795357" y="852.959541872826" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="" function="Transpose@var[]..[]" />
    <DSRevitNodesUI.FamilyTypes type="DSRevitNodesUI.FamilyTypes" guid="2bc4ccef-dee5-4567-b976-89536f8908ce" nickname="Family Types" x="1477.11536736048" y="995.344804871194" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="0" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="1c420759-4d5f-45b4-8310-f1fa07e92c99" nickname="CurveElement.Curve" x="1272.1389132125" y="784.662852583069" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\RevitNodes.dll" function="Revit.Elements.CurveElement.Curve" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="eed8d389-5ad2-4ac0-a270-7d737f487ad0" start_index="0" end="765c3e25-1262-4f2b-ab25-08ece79508f5" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="f46e385f-3b0a-446c-adeb-8d419a480cba" start_index="0" end="765c3e25-1262-4f2b-ab25-08ece79508f5" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fe4c569f-a1b4-46da-8e76-d1b1bd5b6ef4" start_index="0" end="765c3e25-1262-4f2b-ab25-08ece79508f5" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="83f06d4b-59ed-4888-a259-43d12f3d1736" start_index="0" end="13ca5899-91cd-448b-b475-a286eb0fbfba" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="765c3e25-1262-4f2b-ab25-08ece79508f5" start_index="0" end="1c420759-4d5f-45b4-8310-f1fa07e92c99" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ddaba609-2fa0-4d18-be64-1443ad3d08f1" start_index="0" end="83f06d4b-59ed-4888-a259-43d12f3d1736" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="cc3ba87a-cc1f-4db6-99f2-769f3020e0df" start_index="0" end="ddaba609-2fa0-4d18-be64-1443ad3d08f1" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="13ca5899-91cd-448b-b475-a286eb0fbfba" start_index="0" end="357e7a53-361c-4c1e-81ae-83e16213a39a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2bc4ccef-dee5-4567-b976-89536f8908ce" start_index="0" end="357e7a53-361c-4c1e-81ae-83e16213a39a" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="1c420759-4d5f-45b4-8310-f1fa07e92c99" start_index="0" end="83f06d4b-59ed-4888-a259-43d12f3d1736" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Select curve from Revit" x="846.35713721073" y="635.617946335688" />
    <Dynamo.Models.NoteModel text="Select curve from Revit" x="846.35713721073" y="779.687312996161" />
    <Dynamo.Models.NoteModel text="Select curve from Revit" x="846.35713721073" y="921.415745553684" />
    <Dynamo.Models.NoteModel text="Run this graph by opening &quot;Adaptive Component Placement.rfa&quot; from Samples folder." x="1261.91313786918" y="594.234679641806" />
  </Notes>
</Workspace>