<Workspace Version="0.7.0.38229" X="-104.847184747695" Y="368.030209697265" zoom="1.04898954520253" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="6e0ee6ed-5fe7-4080-b022-f0998c929ae6" nickname="UV.ByCoordinates" x="759.373475383396" y="-205.107339430141" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.UV.ByCoordinates@double,double" />
    <Dynamo.Nodes.DSFaceSelection type="Dynamo.Nodes.DSFaceSelection" guid="eb8172db-6635-4b60-9c06-98172061542d" nickname="Select Face" x="4.92071693222216" y="157.954024039753" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="16e58ffa-d140-450b-96cc-558991852bd0-0000e945:16:SURFACE" />
    </Dynamo.Nodes.DSFaceSelection>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="ca608a4e-0430-4cee-a0bb-61e81f198e8b" nickname="Voronoi.ByParametersOnSurface" x="1363.01980605339" y="-147.538842704087" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="Tessellation.dll" function="Tessellation.Voronoi.ByParametersOnSurface@Autodesk.DesignScript.Geometry.UV[],Autodesk.DesignScript.Geometry.Surface" />
    <Dynamo.Nodes.Watch3D type="Dynamo.Nodes.Watch3D" guid="1230060b-9214-4634-a77a-7b8980b7292f" nickname="Watch 3D" x="1658.78019692011" y="-254.651729980827" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <view width="387" height="415">
        <camera pos_x="23.2610960208189" pos_y="23.2610960208189" pos_z="23.2600960208189" look_x="-23.2610960208189" look_y="-23.2610960208189" look_z="-23.2610960208189" />
      </view>
    </Dynamo.Nodes.Watch3D>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="b0a531a0-3933-4a84-9562-c9e502b37870" nickname="ModelCurve.ByCurve" x="1443.5287732384" y="63.1082762178735" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="..\..\..\..\..\..\..\Autodesk\Dynamo07\Core\RevitNodes.dll" function="Revit.Elements.ModelCurve.ByCurve@Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="8381d4da-5689-4e11-9657-d3fba707f049" nickname="Flatten" x="1152.40533058601" y="-136.203051894733" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="" function="Flatten@var[]..[]" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="a77566e9-5471-404b-86ca-5dc9469354c6" nickname="UV.ByCoordinates" x="759.373475383396" y="17.9178364270034" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.UV.ByCoordinates@double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <DSCoreNodesUI.CreateList type="DSCoreNodesUI.CreateList" guid="041ba4d6-2599-47eb-ac87-314cf3af0ad3" nickname="List.Create" x="939.982514888222" y="-124.865314471591" isVisible="true" isUpstreamVisible="true" lacing="Disabled" inputcount="2" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="67fdd93a-e2dc-4ebc-9259-3e1a27ee9a4e" nickname="Code Block" x="301.490191827329" y="-18.2972697560501" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..1..#6;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="f1e63805-3fd4-4a5a-a925-7f515dfdac9b" nickname="Code Block" x="290.683113898607" y="-182.511829973699" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..1..#27;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="6e0ee6ed-5fe7-4080-b022-f0998c929ae6" start_index="0" end="041ba4d6-2599-47eb-ac87-314cf3af0ad3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="eb8172db-6635-4b60-9c06-98172061542d" start_index="0" end="ca608a4e-0430-4cee-a0bb-61e81f198e8b" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="ca608a4e-0430-4cee-a0bb-61e81f198e8b" start_index="0" end="1230060b-9214-4634-a77a-7b8980b7292f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="8381d4da-5689-4e11-9657-d3fba707f049" start_index="0" end="ca608a4e-0430-4cee-a0bb-61e81f198e8b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a77566e9-5471-404b-86ca-5dc9469354c6" start_index="0" end="041ba4d6-2599-47eb-ac87-314cf3af0ad3" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="041ba4d6-2599-47eb-ac87-314cf3af0ad3" start_index="0" end="8381d4da-5689-4e11-9657-d3fba707f049" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="67fdd93a-e2dc-4ebc-9259-3e1a27ee9a4e" start_index="0" end="a77566e9-5471-404b-86ca-5dc9469354c6" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="67fdd93a-e2dc-4ebc-9259-3e1a27ee9a4e" start_index="0" end="a77566e9-5471-404b-86ca-5dc9469354c6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f1e63805-3fd4-4a5a-a925-7f515dfdac9b" start_index="0" end="6e0ee6ed-5fe7-4080-b022-f0998c929ae6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="f1e63805-3fd4-4a5a-a925-7f515dfdac9b" start_index="0" end="6e0ee6ed-5fe7-4080-b022-f0998c929ae6" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Connect these to &#xD;&#xA;make Revit Stuff" x="1443.7398081075" y="5.83495992381376" />
  </Notes>
</Workspace>