<Workspace Version="0.6.2.28307" X="-4.36904761904702" Y="115.952380952381" zoom="1" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.PointBySelection type="Dynamo.Nodes.PointBySelection" guid="6adae558-1d83-4903-a231-a2cf88d4567c" nickname="Point by Selection" x="81" y="14" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="1b788b58-e0bf-484d-9743-fd8172265c3b-0000b9cf" />
    </Dynamo.Nodes.PointBySelection>
    <Dynamo.Nodes.PointBySelection type="Dynamo.Nodes.PointBySelection" guid="7ce00e02-b10b-4b31-b93c-bad204a56499" nickname="Point by Selection" x="82.75" y="107.95" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="1b788b58-e0bf-484d-9743-fd8172265c3b-0000b968" />
    </Dynamo.Nodes.PointBySelection>
    <Dynamo.Nodes.NewList type="Dynamo.Nodes.NewList" guid="8fb17c16-f942-4e1f-b7d2-e69935c70da6" nickname="list" x="257.95" y="47.35" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Input name="index0" />
      <Input name="index1" />
    </Dynamo.Nodes.NewList>
    <Dynamo.Nodes.Transaction type="Dynamo.Nodes.Transaction" guid="265d3748-0dce-4abb-8564-a281c8eba453" nickname="Transaction" x="641.826176494656" y="72.9722865974853" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.Python type="Dynamo.Nodes.Python" guid="1a1d3ed8-9649-41ce-b8c0-d85072ae38fb" nickname="Python Script" x="460.501162790698" y="61.2" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Script>#derived from Nathan Miller's example http://theprovingground.wikidot.com/revit-api-py-curves

# Default imports
import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
import Autodesk
import sys
import clr
path = r'C:\Autodesk\Dynamo\Core'
exec_path = r'C:\Users\Ian\Documents\GitHub\Dynamo\bin\AnyCPU\Debug'
sys.path.append(path)
sys.path.append(exec_path)
clr.AddReference('LibGNet')
from Autodesk.LibG import *
import math

doc = __revit__.ActiveUIDocument.Document
app = __revit__.Application

# get the input points
beginPoint = IN[0]
endPoint = IN[1]

# The __persistent__ dictionary gives you a persistent
# dictionary between runs.  Here we use it to store elements
# we wish to clean up later.

# Initialize if it's not already created.
if 'oldElements' not in __persistent__:
	__persistent__['oldElements'] = []

#delete old elements
if __persistent__['oldElements'].Count &gt; 0:
     count = 0
     for eID in __persistent__['oldElements']:
          doc.Delete( __persistent__['oldElements'][count] )
          count = count + 1

# Clear the dictionary as we've deleted those old elements
__persistent__['oldElements'] = []

lineRefPointArray = ReferencePointArray()
lineRefPointArray.Append(beginPoint)
lineRefPointArray.Append(endPoint)

crv = doc.FamilyCreate.NewCurveByPoints(lineRefPointArray)
crvRef = crv.GeometryCurve
refptarr = ReferencePointArray()

#use for loop to create a series of points
steps = 20
for i in range(0,steps+1):
    pt = crvRef.Evaluate(float(i)/steps,1) # returns and XYZ
    x = pt.X
    y = pt.Y
    z = pt.Z + math.sin(i)*steps 
    myXYZ = XYZ(x,y,z)
    refPt = doc.FamilyCreate.NewReferencePoint(myXYZ)
    __persistent__['oldElements'].Add(refPt.Id)
    refptarr.Append(refPt)
</Script>
    </Dynamo.Nodes.Python>
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="211fc774-26a9-4c0a-8445-959fbee9ffd8" nickname="Watch" x="742.369047619047" y="232.247619047619" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="6adae558-1d83-4903-a231-a2cf88d4567c" start_index="0" end="8fb17c16-f942-4e1f-b7d2-e69935c70da6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7ce00e02-b10b-4b31-b93c-bad204a56499" start_index="0" end="8fb17c16-f942-4e1f-b7d2-e69935c70da6" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="8fb17c16-f942-4e1f-b7d2-e69935c70da6" start_index="0" end="1a1d3ed8-9649-41ce-b8c0-d85072ae38fb" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1a1d3ed8-9649-41ce-b8c0-d85072ae38fb" start_index="0" end="265d3748-0dce-4abb-8564-a281c8eba453" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1a1d3ed8-9649-41ce-b8c0-d85072ae38fb" start_index="0" end="211fc774-26a9-4c0a-8445-959fbee9ffd8" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Create a transaction to wrap the python script." x="576.833333333333" y="12.4166666666666" />
    <Dynamo.Models.NoteModel text="Select two points." x="84" y="200" />
    <Dynamo.Models.NoteModel text="Create a list." x="282" y="147" />
    <Dynamo.Models.NoteModel text="Make a python script." x="456" y="139" />
  </Notes>
</Workspace>