{
    "$type":"DynamoWebServer.Messages.RunCommandsMessage, DynamoWebServer",
    "commands":
    [{
        "$type":"Dynamo.Models.DynamoModel+CreateNodeCommand, DynamoCore",
        "nodeId":"b43c1f0e-d88f-bfd7-8dd8-dc5536c18390",
        "nodeName":"Number",
        "x":720,
        "y":499.5,
        "defaultPosition":false,
        "transformCoordinates":false
    },
    {
        "$type":"Dynamo.Models.DynamoModel+CreateNodeCommand, DynamoCore",
        "nodeId":"b43c1f0e-d88f-bfd7-8dd8-dc5536c18391",
        "nodeName":"Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
        "x":700,
        "y":450,
        "defaultPosition":false,
        "transformCoordinates":false
    }],
    "WorkspaceGuid":"00000000-0000-0000-0000-000000000000"
}