<Workspace Version="0.7.0.42482" X="-483.036277876635" Y="-240.713614924181" zoom="0.689391830488179" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="f46e385f-3b0a-446c-adeb-8d419a480cba" nickname="Select Model Element" x="846.35713721073" y="671.368151070194" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="c222719c-4dcb-4e48-98ea-a81db96bf8ce-000f484f" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="fe4c569f-a1b4-46da-8e76-d1b1bd5b6ef4" nickname="Select Model Element" x="846.35713721073" y="858.775612707248" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="c222719c-4dcb-4e48-98ea-a81db96bf8ce-000f4954" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="83f06d4b-59ed-4888-a259-43d12f3d1736" nickname="Curve.PointAtParameter" x="2125.63666401672" y="675.731192510799" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="ddaba609-2fa0-4d18-be64-1443ad3d08f1" nickname="Code Block" x="1932.95797506884" y="779.905761065762" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..1..#x;" ShouldFocus="false" />
    <Dynamo.Nodes.IntegerSlider type="Dynamo.Nodes.IntegerSlider" guid="cc3ba87a-cc1f-4db6-99f2-769f3020e0df" nickname="Integer Slider" x="1714.99110463659" y="780.800192524122" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Int32>9</System.Int32>
      <Range min="2" max="10" />
    </Dynamo.Nodes.IntegerSlider>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="caa240c5-4e05-486f-a621-ad27b2e0386c" nickname="StructuralFraming.ByCurveLevelUpVectorAndType" x="2919.95439342708" y="736.162507949932" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.StructuralFraming.ByCurveLevelUpVectorAndType@Autodesk.DesignScript.Geometry.Curve,Revit.Elements.Level,Autodesk.DesignScript.Geometry.Vector,Revit.Elements.StructuralType,Revit.Elements.FamilySymbol" />
    <DSRevitNodesUI.Levels type="DSRevitNodesUI.Levels" guid="770e0aad-6923-487b-9c70-110cc93f40e3" nickname="Levels" x="2645.22947467318" y="884.460684332108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="0" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="2f3ece2d-a309-4a8c-8fe2-2fd77837ff23" nickname="Vector.ZAxis" x="2703.22947467318" y="982.746277036018" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Vector.ZAxis" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="6e4bf9ec-6998-4c14-8875-04ab883d4505" nickname="StructuralType.Beam" x="2652.22947467318" y="1081.03186973993" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.StructuralType.Beam" />
    <DSRevitNodesUI.StructuralFramingTypes type="DSRevitNodesUI.StructuralFramingTypes" guid="acf81b3c-c775-45f2-8eaf-52e4a6b4d8ea" nickname="Structural Framing Types" x="2594.22947467318" y="1179.31746244384" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="0" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="0e46950a-6778-4734-bde8-597e3d70a5d3" nickname="Line.ByStartPointEndPoint" x="2377.66103023001" y="770.174724568282" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="ba2153a0-0421-44fd-88c6-6b3defd03886" nickname="Curve.PointAtParameter" x="2119.20839973551" y="859.101477757295" isVisible="true" isUpstreamVisible="true" lacing="CrossProduct" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="cc8c4cd6-7c66-4702-8afd-55737916f0fc" nickname="Element.Geometry" x="1322.81103259426" y="673.937321829045" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="2f1ac553-ab60-4ce7-8c94-933cf543e87b" nickname="Element.Geometry" x="1329.1362829022" y="860.040731202899" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.Element.Geometry" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="f46e385f-3b0a-446c-adeb-8d419a480cba" start_index="0" end="cc8c4cd6-7c66-4702-8afd-55737916f0fc" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="fe4c569f-a1b4-46da-8e76-d1b1bd5b6ef4" start_index="0" end="2f1ac553-ab60-4ce7-8c94-933cf543e87b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="83f06d4b-59ed-4888-a259-43d12f3d1736" start_index="0" end="0e46950a-6778-4734-bde8-597e3d70a5d3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ddaba609-2fa0-4d18-be64-1443ad3d08f1" start_index="0" end="83f06d4b-59ed-4888-a259-43d12f3d1736" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="ddaba609-2fa0-4d18-be64-1443ad3d08f1" start_index="0" end="ba2153a0-0421-44fd-88c6-6b3defd03886" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="cc3ba87a-cc1f-4db6-99f2-769f3020e0df" start_index="0" end="ddaba609-2fa0-4d18-be64-1443ad3d08f1" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="770e0aad-6923-487b-9c70-110cc93f40e3" start_index="0" end="caa240c5-4e05-486f-a621-ad27b2e0386c" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="2f3ece2d-a309-4a8c-8fe2-2fd77837ff23" start_index="0" end="caa240c5-4e05-486f-a621-ad27b2e0386c" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="6e4bf9ec-6998-4c14-8875-04ab883d4505" start_index="0" end="caa240c5-4e05-486f-a621-ad27b2e0386c" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="acf81b3c-c775-45f2-8eaf-52e4a6b4d8ea" start_index="0" end="caa240c5-4e05-486f-a621-ad27b2e0386c" end_index="4" portType="0" />
    <Dynamo.Models.ConnectorModel start="0e46950a-6778-4734-bde8-597e3d70a5d3" start_index="0" end="caa240c5-4e05-486f-a621-ad27b2e0386c" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ba2153a0-0421-44fd-88c6-6b3defd03886" start_index="0" end="0e46950a-6778-4734-bde8-597e3d70a5d3" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="cc8c4cd6-7c66-4702-8afd-55737916f0fc" start_index="0" end="83f06d4b-59ed-4888-a259-43d12f3d1736" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2f1ac553-ab60-4ce7-8c94-933cf543e87b" start_index="0" end="ba2153a0-0421-44fd-88c6-6b3defd03886" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Model Curves have been selected and their element IDs saved with this file" x="845.053422827828" y="791.941875641148" />
    <Dynamo.Models.NoteModel text="Run this graph the DynamoSample.rvt file in the Samples folder located with your Dynamo installation&#xD;&#xA;C:\ProgramData\Dynamo\0.7\samples\Revit" x="848.02524188179" y="499.007945832127" />
    <Dynamo.Models.NoteModel text="Geometry is Seperated from Revit Elements" x="1284.20917026946" y="796.329860797987" />
    <Dynamo.Models.NoteModel text="Create Points along the Lines" x="2116.30362522241" y="805.372993896443" />
    <Dynamo.Models.NoteModel text="Place Structural Framing" x="2917.09029810553" y="694.169961550349" />
    <Dynamo.Models.NoteModel text="Place Structural Framing Relative to some elements selected from a Revit file" x="846.642091297049" y="598.505547102501" />
  </Notes>
</Workspace>