<Workspace Version="1.0.0.384" X="0" Y="0" zoom="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="6889b455-6887-4b0e-8394-22be681c0162" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Sphere.ByCenterPointRadius" x="196" y="204" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Input.DoubleInput guid="6cbd6af1-71a3-414c-a709-43f9a6a8774a" type="CoreNodeModels.Input.DoubleInput" nickname="Number" x="71" y="229" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false">
      <System.Double value="10" />
    </CoreNodeModels.Input.DoubleInput>
    <CoreNodeModels.Watch guid="456e57f3-d06f-4a53-9771-27188ee9cb40" type="CoreNodeModels.Watch" nickname="Watch" x="459" y="207" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="6889b455-6887-4b0e-8394-22be681c0162" start_index="0" end="456e57f3-d06f-4a53-9771-27188ee9cb40" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6cbd6af1-71a3-414c-a709-43f9a6a8774a" start_index="0" end="6889b455-6887-4b0e-8394-22be681c0162" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>