<Workspace Version="0.8.2.1957" X="-84.907074832804" Y="61.8403257029835" zoom="1.00600419002725" Name="Home" RunType="Automatic" RunPeriod="100" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.CodeBlockNodeModel guid="f9dd3ecd-3b7e-4956-8a28-078b238fa12f" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="187" y="151" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" CodeText="0..3;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="fdec3b9b-56ae-4d01-85c2-47b8425e3130" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="360" y="97" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="Autodesk.Point.ByCoordinates(a&lt;1&gt;,a&lt;2&gt;,a&lt;3&gt;);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="f9dd3ecd-3b7e-4956-8a28-078b238fa12f" start_index="0" end="fdec3b9b-56ae-4d01-85c2-47b8425e3130" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
  <Cameras>
    <Camera Name="eb39be19-caad-41f7-ac76-aa6c908a4e96_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
  <Cameras>
    <Camera Name="eb39be19-caad-41f7-ac76-aa6c908a4e96_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>