{
  "Uuid": "5ca0c38e-e614-4513-b690-906014ed432b",
  "IsCustomNode": false,
  "Description": null,
  "Name": "spehere-labels",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "07b8781c8f734721b0e5d86b8484ca97",
      "Inputs": [
        {
          "Id": "62644a8f8ec3449aad70ae2d7f8f2f85",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d8ea8befb0d94bc08035f347ed38981e",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6692355e49144f61a4c36caf1d07696a",
          "Name": "Sphere",
          "Description": "Sphere",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid Sphere cetered at the input Point, with given radius.\n\nSphere.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Sphere"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "f7d2adc42daf4a4fa2e1f533c991d18b",
      "Inputs": [
        {
          "Id": "984137ce54524d3f890870f9592052d6",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1597441220f44cb3820d471650757318",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f8649dcc8f50451ba8caa9da4ff48b31",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "82b0f21cf26749a78e8cd7a8534695dc",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "1..100;",
      "Id": "8b4a5a677eee4333aaa16f50e0f70f99",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "26f538a35e304ae4bee3e884acf958b6",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "NodeType": "ExtensionNode",
      "Id": "49a7d90cd214426dbd1b673caa4dbb12",
      "Inputs": [
        {
          "Id": "bf0b09193fa64f7caae667f4e74ebfce",
          "Name": "",
          "Description": "Node to evaluate.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1176e3043f7d4821b4647f674a99bdfa",
          "Name": "",
          "Description": "Watch contents.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualize the output of node."
    }
  ],
  "Connectors": [
    {
      "Start": "6692355e49144f61a4c36caf1d07696a",
      "End": "bf0b09193fa64f7caae667f4e74ebfce",
      "Id": "e5002bd1a711446cb4da7c6d1f211ff0"
    },
    {
      "Start": "82b0f21cf26749a78e8cd7a8534695dc",
      "End": "62644a8f8ec3449aad70ae2d7f8f2f85",
      "Id": "ded04598f5c84bcca35762407f1d2694"
    },
    {
      "Start": "26f538a35e304ae4bee3e884acf958b6",
      "End": "984137ce54524d3f890870f9592052d6",
      "Id": "2e456c8f3b4a4c55afd46233edae51e6"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.6.0.7787",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Sphere.ByCenterPointRadius",
        "Id": "07b8781c8f734721b0e5d86b8484ca97",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 387.87774726744556,
        "Y": 143.0
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "f7d2adc42daf4a4fa2e1f533c991d18b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 139.0,
        "Y": 139.0
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "8b4a5a677eee4333aaa16f50e0f70f99",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 36.0,
        "Y": 29.0
      },
      {
        "ShowGeometry": true,
        "Name": "Watch",
        "Id": "49a7d90cd214426dbd1b673caa4dbb12",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 852.588869249369,
        "Y": 266.97073058440185
      }
    ],
    "Annotations": [],
    "X": 42.074791980970872,
    "Y": 65.94391697627816,
    "Zoom": 0.8467448192874274
  }
}