<?xml version="1.0"?>
<migrations>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Geometry.GetClosestPoint</oldName>
    <newName>Autodesk.DesignScript.Geometry.Geometry.ClosestPointTo</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.PolySurface.ProjectCurve</oldName>
    <newName>Autodesk.DesignScript.Geometry.Surface.ProjectInputOnto</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.PolyCurve.FilletPlanarPolyCurve</oldName>
    <newName>Autodesk.DesignScript.Geometry.PolyCurve.Fillet</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Rectangle.ByWidthHeight</oldName>
    <newName>Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.ParameterSplit</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.SplitByParameter</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.EllipseArc.ByPlaneRadiiStartAngleSweepAngle</oldName>
    <newName>Autodesk.DesignScript.Geometry.EllipseArc.ByPlaneRadiiAngles</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Vector.AngleBetween</oldName>
    <newName>Autodesk.DesignScript.Geometry.Vector.AngleWithVector</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.ParameterAtDistance</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.ParameterAtSegmentLength</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.PlaneAtDistance</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.PlaneAtSegmentLength</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.PointAtDistance</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.PointAtSegmentLength</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.DistanceAtParameter</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.SegmentLengthAtParameter</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.CoordinateSystemAtDistance</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.CoordinateSystemAtSegmentLength</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.LengthBetweenParameters</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.SegmentLengthBetweenParameters</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.ParameterTrimStart</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.TrimByStartParameter</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.ParameterTrimEnd</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.TrimByEndParameter</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.ParameterTrim</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.TrimByParameter</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.ParameterTrimInterior</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.TrimInteriorByParameter</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.ParameterTrimSegments</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.TrimSegmentsByParameter</newName>
  </priorNameHint>
    <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Surface.ByLoft@Autodesk.DesignScript.Geometry.Curve[],Autodesk.DesignScript.Geometry.Curve</oldName>
    <newName>Autodesk.DesignScript.Geometry.Surface.ByLoft@Autodesk.DesignScript.Geometry.Curve[],Autodesk.DesignScript.Geometry.Curve[]</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Solid.ByLoft@Autodesk.DesignScript.Geometry.Curve[],Autodesk.DesignScript.Geometry.Curve</oldName>
    <newName>Autodesk.DesignScript.Geometry.Solid.ByLoft@Autodesk.DesignScript.Geometry.Curve[],Autodesk.DesignScript.Geometry.Curve[]</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.TSpline.TSplineSurface.Unweld@Autodesk.DesignScript.Geometry.TSpline.TSplineEdge[]</oldName>
    <newName>Autodesk.DesignScript.Geometry.TSpline.TSplineSurface.UnweldEdges@Autodesk.DesignScript.Geometry.TSpline.TSplineEdge[]</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.TSpline.TSplineSurface.Unweld@Autodesk.DesignScript.Geometry.TSpline.TSplineVertex[]</oldName>
    <newName>Autodesk.DesignScript.Geometry.TSpline.TSplineSurface.UnweldVertices@Autodesk.DesignScript.Geometry.TSpline.TSplineVertex[]</newName>
  </priorNameHint>
</migrations>
