<?xml version="1.0"?>
<doc>
    <assembly>
        <name>ProtoGeometry</name>
    </assembly>
    <namespaces>
        <namespace name="Autodesk.DesignScript.Geometry">
            <category>Geometry</category>
        </namespace>
    </namespaces>
    <classes>
        <class name="Autodesk.DesignScript.Geometry.Arc" shortname="arc"/>
        <class name="Autodesk.DesignScript.Geometry.BoundingBox" shortname="boundingBox"/>
        <class name="Autodesk.DesignScript.Geometry.Circle" shortname="circle"/>
        <class name="Autodesk.DesignScript.Geometry.CoordinateSystem" shortname="coordinate"/>
        <class name="Autodesk.DesignScript.Geometry.Cuboid" shortname="cuboid"/>
        <class name="Autodesk.DesignScript.Geometry.Curve" shortname="curve"/>
        <class name="Autodesk.DesignScript.Geometry.Cylinder" shortname="cylinder"/>
        <class name="Autodesk.DesignScript.Geometry.Edge" shortname="edge"/>
        <class name="Autodesk.DesignScript.Geometry.Ellipse" shortname="ellipse"/>
        <class name="Autodesk.DesignScript.Geometry.EllipseArc" shortname="ellipseArc"/>
        <class name="Autodesk.DesignScript.Geometry.Face" shortname="face"/>
        <class name="Autodesk.DesignScript.Geometry.Geometry" shortname="geometry"/>
        <class name="Autodesk.DesignScript.Geometry.Helix" shortname="helix"/>
        <class name="Autodesk.DesignScript.Geometry.IndexGroup" shortname="indexGroup"/>
        <class name="Autodesk.DesignScript.Geometry.Line" shortname="line"/>
        <class name="Autodesk.DesignScript.Geometry.Mesh" shortname="mesh"/>
        <class name="Autodesk.DesignScript.Geometry.NurbsCurve" shortname="nurbsCurve"/>
        <class name="Autodesk.DesignScript.Geometry.NurbsSurface" shortname="nurbsSurface"/>
        <class name="Autodesk.DesignScript.Geometry.Plane" shortname="plane"/>
        <class name="Autodesk.DesignScript.Geometry.Point" shortname="point"/>
        <class name="Autodesk.DesignScript.Geometry.PolyCurve" shortname="polyCurve"/>
        <class name="Autodesk.DesignScript.Geometry.Polygon" shortname="polygon"/>
        <class name="Autodesk.DesignScript.Geometry.PolySurface" shortname="polySurface"/>
        <class name="Autodesk.DesignScript.Geometry.Rectangle" shortname="rectangle"/>
        <class name="Autodesk.DesignScript.Geometry.Solid" shortname="solid"/>
        <class name="Autodesk.DesignScript.Geometry.Sphere" shortname="sphere"/>
        <class name="Autodesk.DesignScript.Geometry.Surface" shortname="surface"/>
        <class name="Autodesk.DesignScript.Geometry.Topology" shortname="topology"/>
        <class name="Autodesk.DesignScript.Geometry.UV" shortname="uv"/>
        <class name="Autodesk.DesignScript.Geometry.Vector" shortname="vector"/>
        <class name="Autodesk.DesignScript.Geometry.Vertex" shortname="vertex"/>
    </classes>
</doc>
