<?xml version="1.0"?>
<migrations>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Geometry.GetClosestPoint</oldName>
    <newName>Autodesk.DesignScript.Geometry.Geometry.ClosestPointTo</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.PolySurface.ProjectCurve</oldName>
    <newName>Autodesk.DesignScript.Geometry.Surface.ProjectInputOnto</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.PolyCurve.FilletPlanarPolyCurve</oldName>
    <newName>Autodesk.DesignScript.Geometry.PolyCurve.Fillet</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Rectangle.ByWidthHeight</oldName>
    <newName>Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.ParameterSplit</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.SplitByParameter</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.DivideByDistanceFromParameter</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.SplitByChordLength</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Curve.DivideByLengthFromParameter</oldName>
    <newName>Autodesk.DesignScript.Geometry.Curve.SplitBySegmentLength</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.EllipseArc.ByPlaneRadiiStartAngleSweepAngle</oldName>
    <newName>Autodesk.DesignScript.Geometry.EllipseArc.ByPlaneRadiiAngles</newName>
  </priorNameHint>
  <priorNameHint>
    <oldName>Autodesk.DesignScript.Geometry.Vector.AngleBetween</oldName>
    <newName>Autodesk.DesignScript.Geometry.Vector.AngleWithVector</newName>
  </priorNameHint>
</migrations>
