<Workspace Version="0.7.2.2921" X="-1928.92819778544" Y="-203.123066205526" zoom="1.67738718458455" Description="" Category="" Name="Home">
  <Elements>
    <DSRevitNodesUI.FamilyTypes type="DSRevitNodesUI.FamilyTypes" guid="58d04cb5-b532-422e-a164-c9b8b6cd47cd" nickname="Family Types" x="110.5" y="147.5" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="0:Family5:Family5" />
    <DSRevitNodesUI.ElementsOfFamilyType type="DSRevitNodesUI.ElementsOfFamilyType" guid="988be3d8-6865-409e-a951-4bfd1daa1bf3" nickname="All Elements of Family Type" x="366.187152712183" y="195.113523811624" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="70b819c2-c2e6-4bcd-b64b-4cc4ac117cb6" nickname="FamilyInstance.Location" x="579.367016963121" y="252.559354136319" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="RevitNodes.dll" function="Revit.Elements.FamilyInstance.Location" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="651b010d-cf5b-492b-bad4-0d3e8969b84f" nickname="List.Chop" x="825.362732543576" y="295.633830709406" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="DSCoreNodes.dll" function="DSCore.List.Chop@var[]..[],int" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="5d940629-98de-499b-9add-be5d075a784c" nickname="Code Block" x="669.513027350678" y="366.794534322578" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="6;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="1d730f2a-6e44-440e-9e4a-195a20e5a1e4" nickname="NurbsCurve.ByPoints" x="992.085066639121" y="309.62436337808" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.NurbsCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[]" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="b28838eb-5f65-4f29-ae33-913becb3036e" nickname="Surface.ByLoft" x="1214.20167595234" y="301.726883935833" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Surface.ByLoft@Autodesk.DesignScript.Geometry.Curve[]" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="58d04cb5-b532-422e-a164-c9b8b6cd47cd" start_index="0" end="988be3d8-6865-409e-a951-4bfd1daa1bf3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="988be3d8-6865-409e-a951-4bfd1daa1bf3" start_index="0" end="70b819c2-c2e6-4bcd-b64b-4cc4ac117cb6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="70b819c2-c2e6-4bcd-b64b-4cc4ac117cb6" start_index="0" end="651b010d-cf5b-492b-bad4-0d3e8969b84f" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="651b010d-cf5b-492b-bad4-0d3e8969b84f" start_index="0" end="1d730f2a-6e44-440e-9e4a-195a20e5a1e4" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5d940629-98de-499b-9add-be5d075a784c" start_index="0" end="651b010d-cf5b-492b-bad4-0d3e8969b84f" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="1d730f2a-6e44-440e-9e4a-195a20e5a1e4" start_index="0" end="b28838eb-5f65-4f29-ae33-913becb3036e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>