<Workspace Version="0.7.2.2921" X="279.548849592723" Y="210.338493564774" zoom="0.741675631188405" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="13eeecf4-62af-4630-b3eb-5c0fb96b2a74" nickname="ReferencePlane.Plane" x="408.554775280899" y="79.7022471910112" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePlane.Plane" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="e9639430-cbaa-4d71-bb78-994e29cefb6e" nickname="ReferencePlane.ByLine" x="195.650280898876" y="69.373595505618" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.ReferencePlane.ByLine@Autodesk.DesignScript.Geometry.Line" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="7fb56d9e-fe56-4a91-b42e-bebcfcc2b467" nickname="Code Block" x="-336.466292134831" y="65.5533707865169" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="Line.ByStartPointEndPoint(Point.ByCoordinates(10,10,10), Point.ByCoordinates(10,0,10));" ShouldFocus="false" />
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="85c1f8c5-00da-4a7e-94c7-655140e39f6a" nickname="Watch" x="651.720505617977" y="77.5758426966293" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="13eeecf4-62af-4630-b3eb-5c0fb96b2a74" start_index="0" end="85c1f8c5-00da-4a7e-94c7-655140e39f6a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="e9639430-cbaa-4d71-bb78-994e29cefb6e" start_index="0" end="13eeecf4-62af-4630-b3eb-5c0fb96b2a74" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="7fb56d9e-fe56-4a91-b42e-bebcfcc2b467" start_index="0" end="e9639430-cbaa-4d71-bb78-994e29cefb6e" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>