<Workspace Version="0.6.2.14024" X="117.12" Y="224.32" zoom="1.2" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.Python type="Dynamo.Nodes.Python" guid="b1d208e9-ff8d-4586-8ada-6e8d9ccfcf6d" nickname="Python Script" x="267.25" y="9.59999999999997" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Script># adapted from Nathan Miller's Proving Ground Blog
# http://wiki.theprovingground.org/revit-api-py-curves


# Default imports
import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
import Autodesk
import clr
import math
 
doc = __revit__.ActiveUIDocument.Document
app = __revit__.Application

scale = IN

xyzs = []
output = []

#use for loop to create a series of points
for i in range(0,20):
    x = math.sin(i)*scale
    y = math.cos(i)*scale
    z = i*scale/2
 
    myXYZ = XYZ(x,y,z)
    xyzs.append(myXYZ)

#create hermite spline
hs = app.Create.NewHermiteSpline(xyzs, False)
output.append(hs)
output.append(xyzs)

OUT = output;</Script>
    </Dynamo.Nodes.Python>
    <Dynamo.Nodes.Watch3D type="Dynamo.Nodes.Watch3D" guid="ada46d91-3dfa-4a65-bcaa-d1ea39312c41" nickname="Watch 3D" x="417.358741258741" y="9.59999999999997" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <view width="209.6" height="257.6">
        <camera pos_x="182.121185494642" pos_y="182.531414092777" pos_z="306.480876757197" look_x="-181.86507054004" look_y="-181.86507054004" look_z="-181.86507054004" />
      </view>
    </Dynamo.Nodes.Watch3D>
    <Dynamo.Nodes.DoubleSliderInput type="Dynamo.Nodes.DoubleSliderInput" guid="99c31498-e06e-4b95-8000-beaf61dde392" nickname="Number Slider" x="-112" y="9.59999999999997" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double value="26.124" min="0" max="100" />
    </Dynamo.Nodes.DoubleSliderInput>
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="9ebd471e-ea8a-4e90-9235-e15b7d06b992" nickname="Watch" x="630.468159601846" y="9.59999999999997" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.First type="Dynamo.Nodes.First" guid="b91d6a40-21e3-4119-a68c-db308af40d09" nickname="First of List" x="430.066666666667" y="-87.2666666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.ModelCurve type="Dynamo.Nodes.ModelCurve" guid="beceb842-2f51-4729-981c-8def253fab62" nickname="Model Curve" x="546.066666666667" y="-88.6" isVisible="true" isUpstreamVisible="true" lacing="Longest">
      <Run>
        <Element>5794f743-c498-4b18-904c-8ea5e434cd54-0000cb35</Element>
      </Run>
    </Dynamo.Nodes.ModelCurve>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="b1d208e9-ff8d-4586-8ada-6e8d9ccfcf6d" start_index="0" end="9ebd471e-ea8a-4e90-9235-e15b7d06b992" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b1d208e9-ff8d-4586-8ada-6e8d9ccfcf6d" start_index="0" end="ada46d91-3dfa-4a65-bcaa-d1ea39312c41" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b1d208e9-ff8d-4586-8ada-6e8d9ccfcf6d" start_index="0" end="b91d6a40-21e3-4119-a68c-db308af40d09" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="99c31498-e06e-4b95-8000-beaf61dde392" start_index="0" end="b1d208e9-ff8d-4586-8ada-6e8d9ccfcf6d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="b91d6a40-21e3-4119-a68c-db308af40d09" start_index="0" end="beceb842-2f51-4729-981c-8def253fab62" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>