<Workspace Version="0.7.0.22524" X="30.9116113366624" Y="98.7335271490706" zoom="0.822695359375" Description="This node represents an upgrade of 0.6.3 ModelCurveFromCurveLoop to 0.7.x." Category="Migration" Name="ModelCurveFromCurveLoop" ID="cc5f75c8-09a6-409c-b61d-2bf4b1b4091d">
  <Elements>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="fbf2e2d5-ec87-4605-8b92-06fd280c4d04" nickname="ModelCurve.ByCurve" x="458.624146251092" y="6.37010835100955" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\RevitNodes.dll" function="Revit.Elements.ModelCurve.ByCurve@Autodesk.DesignScript.Geometry.Curve" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="96c2539d-061d-45ff-84ed-6dad3c823628" nickname="PolyCurve.Curves" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.Curves" />
    <Dynamo.Nodes.Symbol type="Dynamo.Nodes.Symbol" guid="9b83ca75-b4f6-4f91-893d-ee1bde213143" nickname="Input" x="0" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="polyCurve" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output type="Dynamo.Nodes.Output" guid="c75fc7fa-3e84-47dc-afd3-49955b4711fd" nickname="Output" x="703.624146251092" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Symbol value="ModelCurve" />
    </Dynamo.Nodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="fbf2e2d5-ec87-4605-8b92-06fd280c4d04" start_index="0" end="c75fc7fa-3e84-47dc-afd3-49955b4711fd" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="96c2539d-061d-45ff-84ed-6dad3c823628" start_index="0" end="fbf2e2d5-ec87-4605-8b92-06fd280c4d04" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="9b83ca75-b4f6-4f91-893d-ee1bde213143" start_index="0" end="96c2539d-061d-45ff-84ed-6dad3c823628" end_index="0" portType="0" />
  </Connectors>
  <Notes />
</Workspace>