<Workspace Version="2.0.0.4093" X="-1866.68457277717" Y="-1620.21008275207" zoom="0.998328843087185" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Rectangle" resolvedName="Autodesk.DesignScript.Geometry.Rectangle" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Solid" resolvedName="Autodesk.DesignScript.Geometry.Solid" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="06eb7ca7-3e9c-4011-a7eb-08e47cef9671" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1954.10062862083" y="2097.3977868134" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="5;" ShouldFocus="false">
      <OutPortInfo LineIndex="0" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="3669d05c-c741-44f9-87ab-8961e7f5f112" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2145.05331785436" y="1988.12187308034" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="pln = Plane.ByOriginNormal(ctrPt,Vector.ZAxis());&#xA;rect = Rectangle.ByWidthLength(pln,x,x);&#xA;p1 = Point.Origin();&#xA;p2 = Point.ByCoordinates(0,0,(ctrPt.X+x));&#xA;path = Line.ByStartPointEndPoint(p1,p2);&#xA;s = Solid.BySweep(rect,path);" ShouldFocus="false">
      <PortInfo index="0" default="False" name="ctrPt" />
      <PortInfo index="1" default="False" name="x" />
      <OutPortInfo LineIndex="0" />
      <OutPortInfo LineIndex="1" />
      <OutPortInfo LineIndex="2" />
      <OutPortInfo LineIndex="3" />
      <OutPortInfo LineIndex="4" />
      <OutPortInfo LineIndex="5" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="efafb62b-e09f-4850-a0c3-5c14b6d6e66d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.ByCoordinates" x="1948.05240595467" y="1905.37528613162" isVisible="true" isUpstreamVisible="true" lacing="Auto" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="8187805a-cc0d-4220-8595-4ee38bbee079" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Area" x="2830.41463976855" y="1998.54997335565" isVisible="true" isUpstreamVisible="true" lacing="Auto" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Area">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="06eb7ca7-3e9c-4011-a7eb-08e47cef9671" start_index="0" end="3669d05c-c741-44f9-87ab-8961e7f5f112" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3669d05c-c741-44f9-87ab-8961e7f5f112" start_index="5" end="8187805a-cc0d-4220-8595-4ee38bbee079" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="efafb62b-e09f-4850-a0c3-5c14b6d6e66d" start_index="0" end="3669d05c-c741-44f9-87ab-8961e7f5f112" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>