<Workspace Version="0.8.2.1831" X="0" Y="0" zoom="1" Name="Home" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSFunction guid="74e0334b-95b3-485a-8a92-91c23ffc0540" type="Dynamo.Nodes.DSFunction" nickname="Sphere.ByCenterPointRadius" x="509.5" y="283.5" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
  <Presets />
</Workspace>