<Workspace Version="0.8.1.1172" X="0" Y="0" zoom="1" Name="Home" RunType="Automatic" RunPeriod="100" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.DSFunction guid="23cc5233-8dcf-4e01-a85f-831bab1c54e5" type="Dynamo.Nodes.DSFunction" nickname="Point.ByCoordinates" x="607.5" y="485" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction guid="9d4c59ca-ee83-4963-9c16-014c10fef7b1" type="Dynamo.Nodes.DSFunction" nickname="Point.ByCoordinates" x="608.5" y="352" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
  </Elements>
  <Connectors />
  <Notes />
  <Annotations />
</Workspace>