<Workspace Version="0.8.1.1172" X="30" Y="217.196897374702" zoom="1.61933174224344" Name="Home" RunType="Manual" RunPeriod="100" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Nodes.Watch guid="aaa8dff2-a34b-4d7a-950c-3aeeb70e82c7" type="Dynamo.Nodes.Watch" nickname="Watch" x="291.108327192336" y="92.382461311717" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.DSFunction guid="227c1a9c-02d1-4a9c-91aa-ea7e67d222fb" type="Dynamo.Nodes.DSFunction" nickname="Point.Add" x="665" y="67" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.Add@Autodesk.DesignScript.Geometry.Vector" />
    <Dynamo.Nodes.DSFunction guid="ae64d918-eefe-417b-9a57-e9a56509cb26" type="Dynamo.Nodes.DSFunction" nickname="Point.AsVector" x="430" y="93" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.AsVector" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="79286d7e-e41b-4e95-b902-bd6c16085635" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="5.86661753868842" y="-57.7111274871037" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="t1 = Point.ByCoordinates(0, 0, 0);&#xA;t2 = Point.ByCoordinates(0, 0, 0);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="aaa8dff2-a34b-4d7a-950c-3aeeb70e82c7" start_index="0" end="ae64d918-eefe-417b-9a57-e9a56509cb26" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ae64d918-eefe-417b-9a57-e9a56509cb26" start_index="0" end="227c1a9c-02d1-4a9c-91aa-ea7e67d222fb" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="79286d7e-e41b-4e95-b902-bd6c16085635" start_index="0" end="227c1a9c-02d1-4a9c-91aa-ea7e67d222fb" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="79286d7e-e41b-4e95-b902-bd6c16085635" start_index="1" end="aaa8dff2-a34b-4d7a-950c-3aeeb70e82c7" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel guid="1a2758b0-b8b8-4f74-b608-a137a12e2036" text="After hitting &quot;Run&quot; or with Run Automatically enabled, see the geometric entity either in the Background Peview, in Watch 3d, or as data in a Watch node.  Elements will highlight in Background when the node is selected" x="-24177.0903888257" y="-20287.4502956788" />
  </Notes>
  <Annotations />
</Workspace>