<Workspace Version="0.7.2.22072" X="180.647579079298" Y="-370.416634928923" zoom="0.570784129804548" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="149b7468-ec0a-461d-b314-a3cbac481ade" nickname="CoordinateSystem.ByOrigin" x="-93.9454928251202" y="773.169590273776" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin@double,double,double" />
    <Dynamo.Nodes.DoubleInput type="Dynamo.Nodes.DoubleInput" guid="a15191cd-8cfc-491e-bfc0-bead4fb2b7df" nickname="Number" x="-307.122252220017" y="782.507165671617" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double value="0" />
    </Dynamo.Nodes.DoubleInput>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="1fbc0c8b-9c42-4613-877a-f479c8aecf17" nickname="Rectangle.ByWidthHeight" x="232.955125412449" y="782.524504085413" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Rectangle.ByWidthHeight@Autodesk.DesignScript.Geometry.CoordinateSystem,double,double" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="a0cb7f59-e5bf-4a35-881d-06cb64dcbe83" nickname="PolyCurve.Curves" x="500.600360145901" y="778.398790170651" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.Curves" />
    <DSRevitNodesUI.Levels type="DSRevitNodesUI.Levels" guid="2664d40a-676a-4565-9fe0-aa8b8eedf468" nickname="Levels" x="666.191510594481" y="1046.86740491752" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="0:Level 1" />
    <DSCoreNodesUI.BoolSelector type="DSCoreNodesUI.BoolSelector" guid="c31a4e71-30bf-44b0-a3c3-509808e4a16f" nickname="Boolean" x="361.530772952068" y="1405.25253565572" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Boolean>False</System.Boolean>
    </DSCoreNodesUI.BoolSelector>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="63802024-b434-4c3b-8f2a-3ec43babfe1a" nickname="PolyCurve.Curves" x="852.10603344356" y="1355.45240319052" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.Curves" />
    <Dynamo.Nodes.DoubleSlider type="Dynamo.Nodes.DoubleSlider" guid="68a3ded5-6e08-4b23-831d-7c152c3d1e87" nickname="Double Slider" x="-229.047513812453" y="1367.8306040754" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double>4</System.Double>
      <Range min="1" max="4" />
    </Dynamo.Nodes.DoubleSlider>
    <Dynamo.Nodes.DoubleSlider type="Dynamo.Nodes.DoubleSlider" guid="2411be0e-abff-4d32-804c-5e5025a92257" nickname="Double Slider" x="-257.287236592346" y="1197.33259672224" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double>19.89</System.Double>
      <Range min="1" max="20" />
    </Dynamo.Nodes.DoubleSlider>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="9d66d6c7-da84-4ad5-942b-7614b170d647" nickname="FamilyInstance.ByPointAndLevel" x="1072.25383224607" y="1056.66368278702" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="RevitNodes.dll" function="Revit.Elements.FamilyInstance.ByPointAndLevel@Revit.Elements.FamilySymbol,Autodesk.DesignScript.Geometry.Point,Revit.Elements.Level" />
    <DSRevitNodesUI.FamilyTypes type="DSRevitNodesUI.FamilyTypes" guid="8bbb7dd7-33b3-4987-afd1-9a7d65015f7f" nickname="Family Types" x="383.396008039786" y="1154.67041579125" isVisible="true" isUpstreamVisible="true" lacing="Disabled" index="4:Sofa-Pensi:65&quot;" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="1cba4da8-958b-40d0-9f16-7b7811194013" nickname="Curve.EndPoint" x="1059.6840769741" y="1322.53189352196" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.EndPoint" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="6f449ed2-df49-479c-8f52-0d20dbb6a1ff" nickname="PolyCurve.Fillet" x="612.090361084572" y="1343.93176347615" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.PolyCurve.Fillet@double,bool">
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="149b7468-ec0a-461d-b314-a3cbac481ade" start_index="0" end="1fbc0c8b-9c42-4613-877a-f479c8aecf17" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a15191cd-8cfc-491e-bfc0-bead4fb2b7df" start_index="0" end="149b7468-ec0a-461d-b314-a3cbac481ade" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="a15191cd-8cfc-491e-bfc0-bead4fb2b7df" start_index="0" end="149b7468-ec0a-461d-b314-a3cbac481ade" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="a15191cd-8cfc-491e-bfc0-bead4fb2b7df" start_index="0" end="149b7468-ec0a-461d-b314-a3cbac481ade" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="1fbc0c8b-9c42-4613-877a-f479c8aecf17" start_index="0" end="a0cb7f59-e5bf-4a35-881d-06cb64dcbe83" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1fbc0c8b-9c42-4613-877a-f479c8aecf17" start_index="0" end="6f449ed2-df49-479c-8f52-0d20dbb6a1ff" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="2664d40a-676a-4565-9fe0-aa8b8eedf468" start_index="0" end="9d66d6c7-da84-4ad5-942b-7614b170d647" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="c31a4e71-30bf-44b0-a3c3-509808e4a16f" start_index="0" end="6f449ed2-df49-479c-8f52-0d20dbb6a1ff" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="63802024-b434-4c3b-8f2a-3ec43babfe1a" start_index="0" end="1cba4da8-958b-40d0-9f16-7b7811194013" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="68a3ded5-6e08-4b23-831d-7c152c3d1e87" start_index="0" end="6f449ed2-df49-479c-8f52-0d20dbb6a1ff" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="2411be0e-abff-4d32-804c-5e5025a92257" start_index="0" end="1fbc0c8b-9c42-4613-877a-f479c8aecf17" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="2411be0e-abff-4d32-804c-5e5025a92257" start_index="0" end="1fbc0c8b-9c42-4613-877a-f479c8aecf17" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="8bbb7dd7-33b3-4987-afd1-9a7d65015f7f" start_index="0" end="9d66d6c7-da84-4ad5-942b-7614b170d647" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="1cba4da8-958b-40d0-9f16-7b7811194013" start_index="0" end="9d66d6c7-da84-4ad5-942b-7614b170d647" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="6f449ed2-df49-479c-8f52-0d20dbb6a1ff" start_index="0" end="63802024-b434-4c3b-8f2a-3ec43babfe1a" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Wall Distance" x="-151.878732686438" y="1143.97291835697" />
    <Dynamo.Models.NoteModel text="Wall Fillet Radius" x="-163.685728698812" y="1304.29790076451" />
  </Notes>
</Workspace>