<Workspace Version="0.7.2.42284" X="-94.4444118093653" Y="-161.344948504371" zoom="0.894168083312077" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSEdgeSelection type="Dynamo.Nodes.DSEdgeSelection" guid="27828b05-2d9d-4a49-a28a-b41027a21df3" nickname="Select Edge" x="145.94832733215" y="478.418545966357" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="d854cdd2-7ea0-4cc0-bd7b-18891f94b3ee-000082e3:7:LINEAR" />
    </Dynamo.Nodes.DSEdgeSelection>
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="3640ef07-45a1-43aa-bb65-47e217823055" nickname="Watch" x="450.103674300834" y="483.026960314367" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="39313303-9e3d-489f-ba14-7be311b39d4b" nickname="Curve.PointAtParameter" x="439.73474201781" y="631.648323037702" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double">
      <PortInfo index="1" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="4d2cfcd7-94bf-4966-a88d-623bd2ce73f7" nickname="Code Block" x="266" y="670" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..1..#5;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="27828b05-2d9d-4a49-a28a-b41027a21df3" start_index="0" end="3640ef07-45a1-43aa-bb65-47e217823055" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="27828b05-2d9d-4a49-a28a-b41027a21df3" start_index="0" end="39313303-9e3d-489f-ba14-7be311b39d4b" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="4d2cfcd7-94bf-4966-a88d-623bd2ce73f7" start_index="0" end="39313303-9e3d-489f-ba14-7be311b39d4b" end_index="1" portType="0" />
  </Connectors>
  <Notes />
</Workspace>