{
  "Uuid": "ff7b228c-1de7-46af-8ecc-cd95afac1c05",
  "IsCustomNode": false,
  "Description": "",
  "Name": "point_sphere",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "26116d1a2f5d4c7984d193dd98993646",
      "Inputs": [
        {
          "Id": "1a93c180a2234943b0ac342c4785a776",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "79cdfa5452004b83b59fbb2cbd0d1d4f",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6087f21c2c9c46a79b8b9ac103c9de85",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3fc876efb2aa4bbc9a394349821aa368",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double",
      "Id": "433e11aba54244ba89e405cfcaa02a3f",
      "Inputs": [
        {
          "Id": "53287d2c2ff84e4f9c72deba87d0e5fc",
          "Name": "centerPoint",
          "Description": "Point\nDefault value : Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d810a380917a4f82a2a1076e27a2557c",
          "Name": "radius",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9d49152235b34d9faa53786eb0dd53e7",
          "Name": "Sphere",
          "Description": "Sphere",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Solid Sphere cetered at the input Point, with given radius.\n\nSphere.ByCenterPointRadius (centerPoint: Point = Autodesk.DesignScript.Geometry.Point.ByCoordinates(0, 0, 0), radius: double = 1): Sphere"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "56;\n89;\n74;",
      "Id": "f100f86cd64944aa9939de3fc878c1c7",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "faa9a1ba8dcf46d9b284773afddb8465",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b544795a1acc466fa31172aef7f19bb9",
          "Name": "",
          "Description": "Value of expression at line 2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "310217b47858409e9c2665f16be9297d",
          "Name": "",
          "Description": "Value of expression at line 3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    }
  ],
  "Connectors": [
    {
      "Start": "3fc876efb2aa4bbc9a394349821aa368",
      "End": "53287d2c2ff84e4f9c72deba87d0e5fc",
      "Id": "4d552dc362274904902d14d7c670099b",
      "IsHidden": "False"
    },
    {
      "Start": "faa9a1ba8dcf46d9b284773afddb8465",
      "End": "1a93c180a2234943b0ac342c4785a776",
      "Id": "7219fbbe057742519a9f95c4ed89dab0",
      "IsHidden": "False"
    },
    {
      "Start": "b544795a1acc466fa31172aef7f19bb9",
      "End": "79cdfa5452004b83b59fbb2cbd0d1d4f",
      "Id": "28800c16c1414a4591d496b7425663e2",
      "IsHidden": "False"
    },
    {
      "Start": "310217b47858409e9c2665f16be9297d",
      "End": "6087f21c2c9c46a79b8b9ac103c9de85",
      "Id": "571566da1f47466095f449ac42040d0c",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Thumbnail": "",
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.16",
      "Data": {}
    }
  ],
  "Author": "",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.16.0.1640",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Id": "26116d1a2f5d4c7984d193dd98993646",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 259.2000000000001,
        "Y": 63.999999999999986
      },
      {
        "Name": "Sphere.ByCenterPointRadius",
        "ShowGeometry": true,
        "Id": "433e11aba54244ba89e405cfcaa02a3f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 623.60000000000014,
        "Y": 246.8
      },
      {
        "Name": "Code Block",
        "ShowGeometry": true,
        "Id": "f100f86cd64944aa9939de3fc878c1c7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 28.0,
        "Y": 167.0
      }
    ],
    "Annotations": [],
    "X": 0.0,
    "Y": 0.0,
    "Zoom": 1.0
  }
}