{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Revit_GeometryCreation_Surfaces",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "918f7dc4e6d04d6b9b51c329d02db2b2",
      "Inputs": [
        {
          "Id": "38164badfeac4a00b37992ce48c9b94b",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "234060568bab4ed18e6e785c5aed8dc2",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7721e50f27af4caaafa1f1f42b6e4ab3",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1bbd4aba24934948a95fb28a5919ebeb",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "fb265a3222b04d2ab4f726b28bc90c10",
      "Inputs": [
        {
          "Id": "08edf5a93bab4ff2a77e4c3ed861375a",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4719c97b1932494892dfefe03a7796cf",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "42e70bfdd91246e4b57bccb85cf33de8",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "aef6eaa7e1984fb98265607bf012615d",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "e594468a412344b4870884b31915b703",
      "Inputs": [
        {
          "Id": "127428911b814f12b63682ab414c3e5e",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ea5c6ded0abd47fabdc57f0c8e114751",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0cb7c202a9ef43b3b53ecd487a267b88",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6467add41a094c519eb2e111815b68a6",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 10.0,
      "Id": "4f378cbb3c5d4496b11be74d16300d48",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "37fc837d889646269b9e235be1a40e90",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 5.0,
      "Id": "bc1ea09916454e28b57419385b4d812b",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "38953ef23da44d888929d6637fb25512",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Arc.ByThreePoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "f17077267a2b4cc29768fd8e8c31a44a",
      "Inputs": [
        {
          "Id": "c60c574ac65c49d2a9f00f2b539dad43",
          "Name": "firstPoint",
          "Description": "First point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3717b4e1226647efbde27ea7375f4254",
          "Name": "secondPoint",
          "Description": "Second point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "953fae8999294f12b7e2d5f41229e83d",
          "Name": "thirdPoint",
          "Description": "Third point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f2195a6b254b4258803f2ddd7f8da0e0",
          "Name": "Arc",
          "Description": "An Arc",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an arc by providing three sequential points along its circumference.\n\nArc.ByThreePoints (firstPoint: Point, secondPoint: Point, thirdPoint: Point): Arc"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsSurface.ByControlPoints@Autodesk.DesignScript.Geometry.Point[][],int,int",
      "Id": "4859e415f1374590b107c528167769c0",
      "Inputs": [
        {
          "Id": "6e6191a1257d49f9a794c86613b831b4",
          "Name": "controlVertices",
          "Description": "Point[][]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fc3f6b4befe344f2a20715a489a30680",
          "Name": "uDegree",
          "Description": "int\nDefault value : 3",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4aa81e8635644783b06d3f9d819a14f0",
          "Name": "vDegree",
          "Description": "int\nDefault value : 3",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f3c71042517f4f008e4e8c2971c012f7",
          "Name": "NurbsSurface",
          "Description": "NurbsSurface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a NurbsSurface by using explicit control Points, with specified U and V degrees.\n\nNurbsSurface.ByControlPoints (controlVertices: Point[][], uDegree: int = 3, vDegree: int = 3): NurbsSurface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.ImportInstance.ByGeometries@Autodesk.DesignScript.Geometry.Geometry[]",
      "Id": "c1e10fd1974e4374b6ec0766615d3df4",
      "Inputs": [
        {
          "Id": "67e7e07ad4ed4504860d2ea77383bc55",
          "Name": "geometries",
          "Description": "A collection of Geometry\n\nGeometry[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "eeb65b0302d74ebaa880c09ad5ac60a3",
          "Name": "ImportInstance",
          "Description": "ImportInstance",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Import a collection of Geometry (Solid, Curve, Surface, etc) into Revit as an ImportInstance. This variant is much faster than ImportInstance.ByGeometry as it uses a batch method.\n\nImportInstance.ByGeometries (geometries: Geometry[]): ImportInstance"
    },
    {
      "ConcreteType": "CoreNodeModels.CreateList, CoreNodeModels",
      "VariableInputPorts": true,
      "NodeType": "ExtensionNode",
      "Id": "c8658b1166f54b96ad0f6b482220aed8",
      "Inputs": [
        {
          "Id": "a431cdcf129c40798c6f987afbddc794",
          "Name": "item0",
          "Description": "Item Index #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d24a4a5dd4554545b8dd5f8ba2ce831f",
          "Name": "item1",
          "Description": "Item Index #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b60dd6cbbf2a4d07a339d004cc4f0e99",
          "Name": "list",
          "Description": "A list",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Makes a new list out of the given inputs"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.Area",
      "Id": "ceadf6946ef64eb797650f1d795506aa",
      "Inputs": [
        {
          "Id": "89ffa253dd62486eab0d0d31927794fa",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "07778759d60445fe99b4295b34539c1b",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns the total surface area.\n\nSurface.Area: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.PointAtParameter@double,double",
      "Id": "f063f504b2a3435e93bedb8b448f8afd",
      "Inputs": [
        {
          "Id": "bface0f6691946af9944f7e9fc7c8b6c",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7fe7bf608ec74e6489e8e8ddd854ffb8",
          "Name": "u",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ad7a7d94bfe04c0c94587e5ab8d33684",
          "Name": "v",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d7af59054b3b4676821e930af412857a",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "CrossProduct",
      "Description": "Return the Point at specified U and V parameters.\n\nSurface.PointAtParameter (u: double = 0, v: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0..1..0.1;",
      "Id": "cc0a41cb8ccc445481f183efad0eadb1",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "2b35b3cacd3e40ad8ae826a0be6313a1",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "CoreNodeModels.CreateList, CoreNodeModels",
      "VariableInputPorts": true,
      "NodeType": "ExtensionNode",
      "Id": "e99a534aa8cd4a2fbf1e838cc69f2064",
      "Inputs": [
        {
          "Id": "bc5126f993324dfe84ecd74dee923cbc",
          "Name": "item0",
          "Description": "Item Index #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7a761fa3ead848d2a3af43fee7cb2e3d",
          "Name": "item1",
          "Description": "Item Index #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "92e5b85c501947fe92f40290aab4e04b",
          "Name": "list",
          "Description": "A list",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Makes a new list out of the given inputs"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolySurface.ByJoinedSurfaces@Autodesk.DesignScript.Geometry.Surface[]",
      "Id": "b6aa70b0dedd475e97266aeb62fbb70f",
      "Inputs": [
        {
          "Id": "fd07036c38b249ff9578258de4c59caf",
          "Name": "surfaces",
          "Description": "Surfaces to join into polysurface\n\nSurface[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4c73b769a0094c45954aa389a1aa7edd",
          "Name": "PolySurface",
          "Description": "PolySurface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Make Polysurface by joining surfaces.\n\nPolySurface.ByJoinedSurfaces (surfaces: Surface[]): PolySurface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.Area",
      "Id": "43d2acf71aa14bf3a6284bb413e989ef",
      "Inputs": [
        {
          "Id": "3335d9c2ec6f4cf8bc02122b6e09d10b",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "95904cde4f4a4d4dbe84764e6720fe8a",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns the total surface area.\n\nSurface.Area: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.Area",
      "Id": "74aa06879e0d42fc9ff52430687c61d1",
      "Inputs": [
        {
          "Id": "b8cdf7229b1440789979f99513a2f682",
          "Name": "surface",
          "Description": "Autodesk.DesignScript.Geometry.Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9b566af24ff44388af0f0f0b8bb1f807",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns the total surface area.\n\nSurface.Area: double"
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "NodeType": "ExtensionNode",
      "Id": "b12d7c07d64c41dca83e19b14b06982b",
      "Inputs": [
        {
          "Id": "a8be6a1cb3324444a15517a2c1135e3b",
          "Name": "",
          "Description": "Node to evaluate.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9b40435de116412ab17b86953b06d0f6",
          "Name": "",
          "Description": "Watch contents.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualize the output of node."
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "NodeType": "ExtensionNode",
      "Id": "6bc911c00a094a3597332140d6c898cc",
      "Inputs": [
        {
          "Id": "e09b814f871447f497b61bdbdcfbddd3",
          "Name": "",
          "Description": "Node to evaluate.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1ea3ab4165ad4fec945adab231f65e7c",
          "Name": "",
          "Description": "Watch contents.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualize the output of node."
    },
    {
      "ConcreteType": "CoreNodeModels.Watch, CoreNodeModels",
      "NodeType": "ExtensionNode",
      "Id": "b2f1f55ecf2842758cd44f48088f26ef",
      "Inputs": [
        {
          "Id": "fbc9a295d4ac48ea997fd5e935202205",
          "Name": "",
          "Description": "Node to evaluate.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "42abea7cc585497b8d03cfc811f071ff",
          "Name": "",
          "Description": "Watch contents.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Visualize the output of node."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.BySweep2Rails@Autodesk.DesignScript.Geometry.Curve,Autodesk.DesignScript.Geometry.Curve,Autodesk.DesignScript.Geometry.Curve",
      "Id": "b3654f9d298b41568dcac1684b017930",
      "Inputs": [
        {
          "Id": "7f2c5265741f463cacc1b825365e6725",
          "Name": "path",
          "Description": "The input path to sweep along.\n\nCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2d9538bf09be498f92873f2c0dc5d391",
          "Name": "guideRail",
          "Description": "A rail to guide the orientation of the sweep.\n\nCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8c9a4811fc7c4bba8c932def304ce5b9",
          "Name": "profile",
          "Description": "The profile curve to sweep along the path.\n\nCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "aeb7d8a8392b41cc9a4eeefd7bb24a35",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Sweep the cross section curve along a path guided by a two rails\n\nSurface.BySweep2Rails (path: Curve, guideRail: Curve, profile: Curve): Surface"
    },
    {
      "ConcreteType": "Watch3DNodeModels.Watch3D, Watch3DNodeModels",
      "WatchWidth": 320.0,
      "WatchHeight": 457.0,
      "WasExecuted": true,
      "Camera": {
        "Name": "a6ea80d1-292f-4754-af60-4f40882d0c98 Preview",
        "EyeX": -17.0,
        "EyeY": 24.0,
        "EyeZ": 50.0,
        "LookX": 12.0,
        "LookY": -13.0,
        "LookZ": -58.0,
        "UpX": 0.0,
        "UpY": 1.0,
        "UpZ": 0.0
      },
      "NodeType": "ExtensionNode",
      "Id": "a6ea80d1292f4754af604f40882d0c98",
      "Inputs": [
        {
          "Id": "7a6383d4b253403f8d7eb01b9cbece39",
          "Name": "",
          "Description": "Incoming geometry objects.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "da901a31c41c43fe83c047a288278521",
          "Name": "",
          "Description": "Incoming geometry objects.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Shows a dynamic preview of geometry."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "0eb196569e2044a5a335aad9d9085363",
      "Inputs": [
        {
          "Id": "b87152331b34461eac5b8d248ff94a74",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3db0657e803f4c4b84f2da2365910bfe",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8eb1a6c6ccfc4213b88c38049d146cc3",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "307ec73cc9934dcd971c6c027a9d13e2",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": -5.0,
      "Id": "409caf42170f4a5dad697428efb89449",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "015fd19150f54becbbd479e1664e2955",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "a73ee6eaa09e42b8b3879cee68f2d0d7",
      "Inputs": [
        {
          "Id": "16e97c4f38aa428690885d2067a33c46",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "26cce09b9c1b42eeb991fb4e360a2e1b",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b8b28e33b4fc4eebb6bb8909c5aed117",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "cc52357512f44917b36068d0ba36d357",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Arc.ByThreePoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "81798992a49545ec9a156e31c58dee79",
      "Inputs": [
        {
          "Id": "c27809e51bae42d795645e45051d6159",
          "Name": "firstPoint",
          "Description": "First point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "27cffbf1060c425381b1b2d0a8457214",
          "Name": "secondPoint",
          "Description": "Second point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e83b57bdebee43218623525e8eac5007",
          "Name": "thirdPoint",
          "Description": "Third point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "83ea58b2af084ef3b22f8d77deb34c4d",
          "Name": "Arc",
          "Description": "An Arc",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an arc by providing three sequential points along its circumference.\n\nArc.ByThreePoints (firstPoint: Point, secondPoint: Point, thirdPoint: Point): Arc"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Surface.ByLoft@Autodesk.DesignScript.Geometry.Curve[]",
      "Id": "4b1e3b96afc843f49dcb0157f4bc7f29",
      "Inputs": [
        {
          "Id": "b3a9ac379a59411380aab6353252edfc",
          "Name": "crossSections",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "39b8f4ed15354750aa4d5e57c2e85f88",
          "Name": "Surface",
          "Description": "Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a Surface by lofting between input cross section Curves.\n\nSurface.ByLoft (crossSections: Curve[]): Surface"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 5.0,
      "Id": "2cd90c1faed3402a95895c94e3f30ad8",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d3e3a2e977af4d8ea2069e88d4ffa84d",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.Extrude@double",
      "Id": "660a5c8ec82845ff849e2d65e04c7206",
      "Inputs": [
        {
          "Id": "3b4270266bbb4da785f52924ee6f80f9",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "581bdb3f82e243728bd4db7a69991857",
          "Name": "distance",
          "Description": "The distance to extrude the curve\n\ndouble\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "949c3048dd204a9abdae15591d8ddaca",
          "Name": "Surface",
          "Description": "The extruded Surface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Extrudes a Curve in the normal Vector direction\n\nCurve.Extrude (distance: double = 1): Surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "10;",
      "Id": "3a3f07a68c804a83a47fefc0d476644d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "09e41ceb42354a5ca3f505b4b8ad724a",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Arc.ByThreePoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "1981a0822ade440f9ea76ab988fcf810",
      "Inputs": [
        {
          "Id": "8fe3040390dd42448feabd2d5c8dc824",
          "Name": "firstPoint",
          "Description": "First point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "677c1ee4d34d4ee190f3e556c6188adc",
          "Name": "secondPoint",
          "Description": "Second point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ae121b23a7cf493a8bbdc7653020e3fa",
          "Name": "thirdPoint",
          "Description": "Third point along the curve\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4514e981418e4a3ab83ca452c609c1a0",
          "Name": "Arc",
          "Description": "An Arc",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create an arc by providing three sequential points along its circumference.\n\nArc.ByThreePoints (firstPoint: Point, secondPoint: Point, thirdPoint: Point): Arc"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "116a1d2d3ca94ae585fed101a18f2eac",
      "Inputs": [
        {
          "Id": "a478007887f84e28bee64451396b556c",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2f053e28c72948afb80dc44cf6cf8dc8",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "08874e2d23124fa5ab2e1665fcd1c3d7",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "690a600b03324f64bcb86fa5200f83bd",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 5.0,
      "Id": "1dd46e987f4c40dfa8155456c8608647",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b3aacfc6c7014ea797a04022a6e5432e",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 10.0,
      "Id": "65c95e395de245a28a5e20dc073fe158",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "babd95e627964205b4b27b303cf2b36e",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 15.0,
      "Id": "d03279335a8a4f7e9e7cbfbcf111f662",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "8c19662c8e324893a6756ac32437400a",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "a99d0d448b5c47cd94e805248cbe85cc",
      "Inputs": [
        {
          "Id": "bf4c3fb20b8b46668a1ef08739f14245",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a52456212acc406485e7a402e830fa87",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e6241f007a054d99ac456b618b383490",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2757d1051f424e55bd52a507f30aea32",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "87920b6b93124720beeb2b5326f55805",
      "Inputs": [
        {
          "Id": "f40bf67c57c8439cbf60cf760a804c2e",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6a1e9e2e40e8483ca0740f467f72ed83",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3138bf93e1bd49e38e403b26300f36de",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f6d1656097fa45aaaf45b2fcb128a1e9",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": -10.0,
      "Id": "5f44177683ed4b959a2e0c00564ad859",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "6cd0f343b6804dafad7d7f9b2fb011e5",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "4562ee056aa24a6689ac1cf5319ece2e",
      "Inputs": [
        {
          "Id": "83a6cea386424af5ae5431c641ac6f98",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "768edc6e60d34cadaa901c498238f749",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b297f5ce25fa44bda8b29a6aa99b8bdd",
          "Name": "z",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f8ac966bd3a140b08ce2fff56fa9c04c",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "36f5b14fe48d43d69ccd0a066e56fc2e",
      "Inputs": [
        {
          "Id": "c5ce7e45d8d449bb97b03d7d4693284d",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "99b48f814630451bb8a61956a505367b",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b33e32b9e7434189a2c636a26f1b3df4",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 10.0,
      "Id": "d60bbc4ca6df437bbdf7887ce70173b3",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "e6553ea5f0964a6199f637c530cb2a53",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Form.ByLoftCrossSections@Revit.GeometryReferences.ElementCurveReference[],bool",
      "Id": "ae4bfdfe524a4a5cbd6475fd56be89af",
      "Inputs": [
        {
          "Id": "79f855eee1334f3e9abe8d5631706280",
          "Name": "curves",
          "Description": "ElementCurveReference[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "28ab14022855434f9788086ba22ee409",
          "Name": "isSolid",
          "Description": "bool\nDefault value : true",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a7b8ed37855d4b3fab1a9aaa8fdf88f8",
          "Name": "Form",
          "Description": "Form",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a Form by lofting a list of curves\n\nForm.ByLoftCrossSections (curves: ElementCurveReference[], isSolid: bool = true): Form"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.ModelCurve.ReferenceCurveByCurve@Autodesk.DesignScript.Geometry.Curve",
      "Id": "799b4dce33ec4a2585187d988f7e267a",
      "Inputs": [
        {
          "Id": "6fdc5a96623047d0b200066a5ad847a8",
          "Name": "curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a211cca00c174041b00668c671db1510",
          "Name": "ModelCurve",
          "Description": "ModelCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Construct a Revit ModelCurve element from a Curve\n\nModelCurve.ReferenceCurveByCurve (curve: Curve): ModelCurve"
    }
  ],
  "Connectors": [
    {
      "Start": "1bbd4aba24934948a95fb28a5919ebeb",
      "End": "c60c574ac65c49d2a9f00f2b539dad43",
      "Id": "b8ea02782672461bb82929f1cc0d4860"
    },
    {
      "Start": "1bbd4aba24934948a95fb28a5919ebeb",
      "End": "c27809e51bae42d795645e45051d6159",
      "Id": "9d169e18857c4fb1b7b48851a137d0ef"
    },
    {
      "Start": "aef6eaa7e1984fb98265607bf012615d",
      "End": "953fae8999294f12b7e2d5f41229e83d",
      "Id": "59359e3037db439c803ad71ef343f681"
    },
    {
      "Start": "6467add41a094c519eb2e111815b68a6",
      "End": "3717b4e1226647efbde27ea7375f4254",
      "Id": "3bee674c6f164e5690a839be3fe37234"
    },
    {
      "Start": "37fc837d889646269b9e235be1a40e90",
      "End": "08edf5a93bab4ff2a77e4c3ed861375a",
      "Id": "f8adf2f477d349cb9fe614efd5cfc9e3"
    },
    {
      "Start": "37fc837d889646269b9e235be1a40e90",
      "End": "3db0657e803f4c4b84f2da2365910bfe",
      "Id": "e6db03af41bb4e779d32ee7c1fdd48af"
    },
    {
      "Start": "38953ef23da44d888929d6637fb25512",
      "End": "0cb7c202a9ef43b3b53ecd487a267b88",
      "Id": "37bbaa860b894e2cb9ec849d0d675d19"
    },
    {
      "Start": "f2195a6b254b4258803f2ddd7f8da0e0",
      "End": "2d9538bf09be498f92873f2c0dc5d391",
      "Id": "6b87061e96b748aabe4859c08613a804"
    },
    {
      "Start": "f2195a6b254b4258803f2ddd7f8da0e0",
      "End": "d24a4a5dd4554545b8dd5f8ba2ce831f",
      "Id": "115356e4f141479498979288a2985a5c"
    },
    {
      "Start": "f3c71042517f4f008e4e8c2971c012f7",
      "End": "7a6383d4b253403f8d7eb01b9cbece39",
      "Id": "94064ea11b54483795bd2b2032cd0c76"
    },
    {
      "Start": "b60dd6cbbf2a4d07a339d004cc4f0e99",
      "End": "b3a9ac379a59411380aab6353252edfc",
      "Id": "171dd6a495424b7286a134ed622f87c3"
    },
    {
      "Start": "b60dd6cbbf2a4d07a339d004cc4f0e99",
      "End": "6fdc5a96623047d0b200066a5ad847a8",
      "Id": "3907433717e3486fb3cdd3f5ea3a62fe"
    },
    {
      "Start": "07778759d60445fe99b4295b34539c1b",
      "End": "fbc9a295d4ac48ea997fd5e935202205",
      "Id": "8d1e21b04014433cb558540e27f7ba9b"
    },
    {
      "Start": "d7af59054b3b4676821e930af412857a",
      "End": "6e6191a1257d49f9a794c86613b831b4",
      "Id": "e8c5395ecaa848af972525827ace00de"
    },
    {
      "Start": "2b35b3cacd3e40ad8ae826a0be6313a1",
      "End": "7fe7bf608ec74e6489e8e8ddd854ffb8",
      "Id": "a1d73097471a4c30b6af045829ea6fe7"
    },
    {
      "Start": "2b35b3cacd3e40ad8ae826a0be6313a1",
      "End": "ad7a7d94bfe04c0c94587e5ab8d33684",
      "Id": "996854dcd3f84ee8ac96b01ab51e11b9"
    },
    {
      "Start": "92e5b85c501947fe92f40290aab4e04b",
      "End": "fd07036c38b249ff9578258de4c59caf",
      "Id": "7ef062409a2f46e8868d9da1c440f990"
    },
    {
      "Start": "4c73b769a0094c45954aa389a1aa7edd",
      "End": "b8cdf7229b1440789979f99513a2f682",
      "Id": "b1da5879a2a44a818807f0da42489c7c"
    },
    {
      "Start": "95904cde4f4a4d4dbe84764e6720fe8a",
      "End": "a8be6a1cb3324444a15517a2c1135e3b",
      "Id": "4b052337bc5d4267b124de12144aa865"
    },
    {
      "Start": "9b566af24ff44388af0f0f0b8bb1f807",
      "End": "e09b814f871447f497b61bdbdcfbddd3",
      "Id": "83ce0ae4416b42b786facd9668656d10"
    },
    {
      "Start": "aeb7d8a8392b41cc9a4eeefd7bb24a35",
      "End": "67e7e07ad4ed4504860d2ea77383bc55",
      "Id": "450603c94d5745ffb1ee2dc9f7efe94b"
    },
    {
      "Start": "aeb7d8a8392b41cc9a4eeefd7bb24a35",
      "End": "bface0f6691946af9944f7e9fc7c8b6c",
      "Id": "c80ff8e55278480aba6f7e3dba93be69"
    },
    {
      "Start": "aeb7d8a8392b41cc9a4eeefd7bb24a35",
      "End": "7a761fa3ead848d2a3af43fee7cb2e3d",
      "Id": "90d32923e06349a6b63eaf26ae8c07af"
    },
    {
      "Start": "aeb7d8a8392b41cc9a4eeefd7bb24a35",
      "End": "89ffa253dd62486eab0d0d31927794fa",
      "Id": "aea09f0aed85470c9bd645fc019f951f"
    },
    {
      "Start": "307ec73cc9934dcd971c6c027a9d13e2",
      "End": "e83b57bdebee43218623525e8eac5007",
      "Id": "5fd784b6fe094797b4a496cb360f21af"
    },
    {
      "Start": "307ec73cc9934dcd971c6c027a9d13e2",
      "End": "8fe3040390dd42448feabd2d5c8dc824",
      "Id": "6d925908407d46319c62625059554df2"
    },
    {
      "Start": "015fd19150f54becbbd479e1664e2955",
      "End": "16e97c4f38aa428690885d2067a33c46",
      "Id": "324b31ec6c824e6391021238c5eb0cc0"
    },
    {
      "Start": "cc52357512f44917b36068d0ba36d357",
      "End": "27cffbf1060c425381b1b2d0a8457214",
      "Id": "ab9e19e633fd468f92e606c5c30b24d1"
    },
    {
      "Start": "83ea58b2af084ef3b22f8d77deb34c4d",
      "End": "8c9a4811fc7c4bba8c932def304ce5b9",
      "Id": "70f2369c6bf84ebb9e3ccd1584bb66e3"
    },
    {
      "Start": "39b8f4ed15354750aa4d5e57c2e85f88",
      "End": "3335d9c2ec6f4cf8bc02122b6e09d10b",
      "Id": "8f28366346154acfacc1969c7dbb91fe"
    },
    {
      "Start": "39b8f4ed15354750aa4d5e57c2e85f88",
      "End": "bc5126f993324dfe84ecd74dee923cbc",
      "Id": "87ab203921bb43bda3f02bdb60df801e"
    },
    {
      "Start": "d3e3a2e977af4d8ea2069e88d4ffa84d",
      "End": "26cce09b9c1b42eeb991fb4e360a2e1b",
      "Id": "146f2dfd59a04a2994ce6f292b992bb8"
    },
    {
      "Start": "09e41ceb42354a5ca3f505b4b8ad724a",
      "End": "581bdb3f82e243728bd4db7a69991857",
      "Id": "e5c9c84f1e1a404b8060739b44df8d4c"
    },
    {
      "Start": "4514e981418e4a3ab83ca452c609c1a0",
      "End": "7f2c5265741f463cacc1b825365e6725",
      "Id": "7accaa7515a146cd9133a04c3f0a3de1"
    },
    {
      "Start": "4514e981418e4a3ab83ca452c609c1a0",
      "End": "3b4270266bbb4da785f52924ee6f80f9",
      "Id": "2755cfb40fee40c9bd3d2dce4b51134b"
    },
    {
      "Start": "690a600b03324f64bcb86fa5200f83bd",
      "End": "677c1ee4d34d4ee190f3e556c6188adc",
      "Id": "817a12b5297e4ae78e1097e9217051e6"
    },
    {
      "Start": "b3aacfc6c7014ea797a04022a6e5432e",
      "End": "a478007887f84e28bee64451396b556c",
      "Id": "13f464bbafd44df6a83d856ac491d85f"
    },
    {
      "Start": "babd95e627964205b4b27b303cf2b36e",
      "End": "2f053e28c72948afb80dc44cf6cf8dc8",
      "Id": "b8d515176e284b5ea31e9093894da0dc"
    },
    {
      "Start": "babd95e627964205b4b27b303cf2b36e",
      "End": "08874e2d23124fa5ab2e1665fcd1c3d7",
      "Id": "1fccf5d857b2471490b68851d24cf173"
    },
    {
      "Start": "8c19662c8e324893a6756ac32437400a",
      "End": "bf4c3fb20b8b46668a1ef08739f14245",
      "Id": "2192511318db4088a1ca02c6d812b2b4"
    },
    {
      "Start": "8c19662c8e324893a6756ac32437400a",
      "End": "a52456212acc406485e7a402e830fa87",
      "Id": "488ca69a33f64096a3860400f2085963"
    },
    {
      "Start": "2757d1051f424e55bd52a507f30aea32",
      "End": "ae121b23a7cf493a8bbdc7653020e3fa",
      "Id": "c7b7acad72ed470f8c34345b820514ab"
    },
    {
      "Start": "f6d1656097fa45aaaf45b2fcb128a1e9",
      "End": "c5ce7e45d8d449bb97b03d7d4693284d",
      "Id": "4d81c0e778aa418daaf50f897eba2d7d"
    },
    {
      "Start": "6cd0f343b6804dafad7d7f9b2fb011e5",
      "End": "768edc6e60d34cadaa901c498238f749",
      "Id": "55e6e00498c440649702fe5845227e27"
    },
    {
      "Start": "6cd0f343b6804dafad7d7f9b2fb011e5",
      "End": "6a1e9e2e40e8483ca0740f467f72ed83",
      "Id": "fbae9314b1a94efea2583f83d5077457"
    },
    {
      "Start": "f8ac966bd3a140b08ce2fff56fa9c04c",
      "End": "99b48f814630451bb8a61956a505367b",
      "Id": "2953546a474047c79481f630fba1b5f2"
    },
    {
      "Start": "b33e32b9e7434189a2c636a26f1b3df4",
      "End": "a431cdcf129c40798c6f987afbddc794",
      "Id": "2663136276f04ffe9922d0e18080a550"
    },
    {
      "Start": "e6553ea5f0964a6199f637c530cb2a53",
      "End": "f40bf67c57c8439cbf60cf760a804c2e",
      "Id": "9d1122d54ad740eeaf9a6ce186cc0e2e"
    },
    {
      "Start": "a211cca00c174041b00668c671db1510",
      "End": "79f855eee1334f3e9abe8d5631706280",
      "Id": "849815bb658f4ff8a513a5cdd13b0f1a"
    }
  ],
  "Dependencies": [],
  "Bindings": [
    {
      "NodeId": "c1e10fd1-974e-4374-b6ec-0766615d3df4",
      "Binding": {
        "ByGeometries_InClassDecl-1_InFunctionScope-1_Instance0_c1e10fd1-974e-4374-b6ec-0766615d3df4": "PFNPQVAtRU5WOkVudmVsb3BlIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhtbG5zOnhzZD0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiIHhtbG5zOlNPQVAtRU5DPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VuY29kaW5nLyIgeG1sbnM6U09BUC1FTlY9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW52ZWxvcGUvIiB4bWxuczpjbHI9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vc29hcC9lbmNvZGluZy9jbHIvMS4wIiBTT0FQLUVOVjplbmNvZGluZ1N0eWxlPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VuY29kaW5nLyI+DQo8U09BUC1FTlY6Qm9keT4NCjxhMTpDYWxsU2l0ZV94MDAyQl9UcmFjZVNlcmlhbGlzZXJIZWxwZXIgaWQ9InJlZi0xIiB4bWxuczphMT0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9jbHIvbnNhc3NlbS9Qcm90b0NvcmUvUHJvdG9Db3JlJTJDJTIwVmVyc2lvbiUzRDIuMC4xLjQzNTclMkMlMjBDdWx0dXJlJTNEbmV1dHJhbCUyQyUyMFB1YmxpY0tleVRva2VuJTNEbnVsbCI+DQo8TnVtYmVyT2ZFbGVtZW50cz4xPC9OdW1iZXJPZkVsZW1lbnRzPg0KPEJhc2UtMF9IYXNEYXRhPnRydWU8L0Jhc2UtMF9IYXNEYXRhPg0KPEJhc2UtMF9EYXRhIGlkPSJyZWYtMyI+UEZOUFFWQXRSVTVXT2tWdWRtVnNiM0JsSUhodGJHNXpPbmh6YVQwaWFIUjBjRG92TDNkM2R5NTNNeTV2Y21jdk1qQXdNUzlZVFV4VFkyaGxiV0V0YVc1emRHRnVZMlVpSUhodGJHNXpPbmh6WkQwaWFIUjBjRG92TDNkM2R5NTNNeTV2Y21jdk1qQXdNUzlZVFV4VFkyaGxiV0VpSUhodGJHNXpPbE5QUVZBdFJVNURQU0pvZEhSd09pOHZjMk5vWlcxaGN5NTRiV3h6YjJGd0xtOXlaeTl6YjJGd0wyVnVZMjlrYVc1bkx5SWdlRzFzYm5NNlUwOUJVQzFGVGxZOUltaDBkSEE2THk5elkyaGxiV0Z6TG5odGJITnZZWEF1YjNKbkwzTnZZWEF2Wlc1MlpXeHZjR1V2SWlCNGJXeHVjenBqYkhJOUltaDBkSEE2THk5elkyaGxiV0Z6TG0xcFkzSnZjMjltZEM1amIyMHZjMjloY0M5bGJtTnZaR2x1Wnk5amJISXZNUzR3SWlCVFQwRlFMVVZPVmpwbGJtTnZaR2x1WjFOMGVXeGxQU0pvZEhSd09pOHZjMk5vWlcxaGN5NTRiV3h6YjJGd0xtOXlaeTl6YjJGd0wyVnVZMjlrYVc1bkx5SStEUW84VTA5QlVDMUZUbFk2UW05a2VUNE5DanhoTVRwVFpYSnBZV3hwZW1GaWJHVkpaQ0JwWkQwaWNtVm1MVEVpSUhodGJHNXpPbUV4UFNKb2RIUndPaTh2YzJOb1pXMWhjeTV0YVdOeWIzTnZablF1WTI5dEwyTnNjaTl1YzJGemMyVnRMMUpsZG1sMFUyVnlkbWxqWlhNdVVHVnljMmx6ZEdWdVkyVXZVbVYyYVhSVFpYSjJhV05sY3lVeVF5VXlNRlpsY25OcGIyNGxNMFF5TGpBdU1DNDBNell3SlRKREpUSXdRM1ZzZEhWeVpTVXpSRzVsZFhSeVlXd2xNa01sTWpCUWRXSnNhV05MWlhsVWIydGxiaVV6Ukc1MWJHd2lQZzBLUEhOMGNtbHVaMGxFSUdsa1BTSnlaV1l0TXlJK09ETTVZV0kyT0dNdE5EWTNNQzAwTUdWaUxUbGpZMll0WkRReVpXTmxaVFZsT1RVMkxUQXdNREF3T1RoaFBDOXpkSEpwYm1kSlJENE5DanhwYm5SSlJENHlORFF5UEM5cGJuUkpSRDROQ2p3dllURTZVMlZ5YVdGc2FYcGhZbXhsU1dRK0RRbzhMMU5QUVZBdFJVNVdPa0p2WkhrK0RRbzhMMU5QUVZBdFJVNVdPa1Z1ZG1Wc2IzQmxQZzBLPC9CYXNlLTBfRGF0YT4NCjxCYXNlLTBfSGFzTmVzdGVkRGF0YT5mYWxzZTwvQmFzZS0wX0hhc05lc3RlZERhdGE+DQo8L2ExOkNhbGxTaXRlX3gwMDJCX1RyYWNlU2VyaWFsaXNlckhlbHBlcj4NCjwvU09BUC1FTlY6Qm9keT4NCjwvU09BUC1FTlY6RW52ZWxvcGU+DQo="
      }
    }
  ],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.4357",
      "RunType": "Automatic",
      "RunPeriod": "100"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "918f7dc4e6d04d6b9b51c329d02db2b2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24863.5725084611,
        "Y": -19988.0843072235
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "fb265a3222b04d2ab4f726b28bc90c10",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24863.5725084611,
        "Y": -19690.2362488626
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "e594468a412344b4870884b31915b703",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24863.5725084611,
        "Y": -19837.7921779339
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "4f378cbb3c5d4496b11be74d16300d48",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -25017.8259159932,
        "Y": -19653.407616734
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "bc1ea09916454e28b57419385b4d812b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -25017.8259159932,
        "Y": -19806.8715331044
      },
      {
        "ShowGeometry": true,
        "Name": "Arc.ByThreePoints",
        "Id": "f17077267a2b4cc29768fd8e8c31a44a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24471.4587779644,
        "Y": -19800.131380836
      },
      {
        "ShowGeometry": true,
        "Name": "NurbsSurface.ByControlPoints",
        "Id": "4859e415f1374590b107c528167769c0",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22398.890979387,
        "Y": -19203.6985393764
      },
      {
        "ShowGeometry": true,
        "Name": "ImportInstance.ByGeometries",
        "Id": "c1e10fd1974e4374b6ec0766615d3df4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22861.9182723749,
        "Y": -20305.5957145932
      },
      {
        "ShowGeometry": true,
        "Name": "List.Create",
        "Id": "c8658b1166f54b96ad0f6b482220aed8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24121.1518216568,
        "Y": -19985.530529506
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.Area",
        "Id": "ceadf6946ef64eb797650f1d795506aa",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22497.8303992478,
        "Y": -19897.3449926722
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.PointAtParameter",
        "Id": "f063f504b2a3435e93bedb8b448f8afd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22800.5374418187,
        "Y": -19207.7207778656
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "cc0a41cb8ccc445481f183efad0eadb1",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22915.5650716381,
        "Y": -19160.6295255138
      },
      {
        "ShowGeometry": true,
        "Name": "List.Create",
        "Id": "e99a534aa8cd4a2fbf1e838cc69f2064",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22857.3737395323,
        "Y": -19786.7403221816
      },
      {
        "ShowGeometry": true,
        "Name": "PolySurface.ByJoinedSurfaces",
        "Id": "b6aa70b0dedd475e97266aeb62fbb70f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22707.9993462582,
        "Y": -19792.3667753704
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.Area",
        "Id": "43d2acf71aa14bf3a6284bb413e989ef",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22497.8303992478,
        "Y": -19981.9853133271
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.Area",
        "Id": "74aa06879e0d42fc9ff52430687c61d1",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22497.8303992478,
        "Y": -19792.1378651291
      },
      {
        "ShowGeometry": true,
        "Name": "Watch",
        "Id": "b12d7c07d64c41dca83e19b14b06982b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22292.5588455331,
        "Y": -19988.3739647029
      },
      {
        "ShowGeometry": true,
        "Name": "Watch",
        "Id": "6bc911c00a094a3597332140d6c898cc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22292.5588455331,
        "Y": -19786.6610509926
      },
      {
        "ShowGeometry": true,
        "Name": "Watch",
        "Id": "b2f1f55ecf2842758cd44f48088f26ef",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22292.5588455331,
        "Y": -19891.0771475015
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.BySweep2Rails",
        "Id": "b3654f9d298b41568dcac1684b017930",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23694.9144401224,
        "Y": -19617.9788885921
      },
      {
        "ShowGeometry": true,
        "Name": "Watch 3D",
        "Id": "a6ea80d1292f4754af604f40882d0c98",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22123.7078068906,
        "Y": -19347.8518718078
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "0eb196569e2044a5a335aad9d9085363",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24863.5725084611,
        "Y": -19371.1809134497
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "409caf42170f4a5dad697428efb89449",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -25017.8259159932,
        "Y": -19516.5935931663
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "a73ee6eaa09e42b8b3879cee68f2d0d7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24863.5725084611,
        "Y": -19514.1323928564
      },
      {
        "ShowGeometry": true,
        "Name": "Arc.ByThreePoints",
        "Id": "81798992a49545ec9a156e31c58dee79",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24471.4587779644,
        "Y": -19464.7102154558
      },
      {
        "ShowGeometry": true,
        "Name": "Surface.ByLoft",
        "Id": "4b1e3b96afc843f49dcb0157f4bc7f29",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23732.9144401224,
        "Y": -19904.0122180635
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "2cd90c1faed3402a95895c94e3f30ad8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -25017.8259159932,
        "Y": -19452.2001504071
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.Extrude",
        "Id": "660a5c8ec82845ff849e2d65e04c7206",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23674.9144401224,
        "Y": -19331.9455591207
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "3a3f07a68c804a83a47fefc0d476644d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23841.6241165446,
        "Y": -19245.2045683088
      },
      {
        "ShowGeometry": true,
        "Name": "Arc.ByThreePoints",
        "Id": "1981a0822ade440f9ea76ab988fcf810",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24471.4587779644,
        "Y": -19068.5984799728
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "116a1d2d3ca94ae585fed101a18f2eac",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24863.5725084611,
        "Y": -19170.5037128366
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "1dd46e987f4c40dfa8155456c8608647",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -25017.8259159932,
        "Y": -19153.1270914921
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "65c95e395de245a28a5e20dc073fe158",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -25017.8259159932,
        "Y": -19080.6822854514
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "d03279335a8a4f7e9e7cbfbcf111f662",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -25017.8259159932,
        "Y": -18995.603982949
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "a99d0d448b5c47cd94e805248cbe85cc",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24865.5865384285,
        "Y": -19012.9806042934
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "87920b6b93124720beeb2b5326f55805",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24863.5725084611,
        "Y": -20304.484988543
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "5f44177683ed4b959a2e0c00564ad859",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -25017.8259159932,
        "Y": -20144.4452600736
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "4562ee056aa24a6689ac1cf5319ece2e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24863.5725084611,
        "Y": -20154.1928592534
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "36f5b14fe48d43d69ccd0a066e56fc2e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24486.9036506054,
        "Y": -20188.12640655
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "d60bbc4ca6df437bbdf7887ce70173b3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -25017.8259159932,
        "Y": -20273.2479544427
      },
      {
        "ShowGeometry": true,
        "Name": "Form.ByLoftCrossSections",
        "Id": "ae4bfdfe524a4a5cbd6475fd56be89af",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22586.5445982076,
        "Y": -20518.126024631
      },
      {
        "ShowGeometry": true,
        "Name": "ModelCurve.ReferenceCurveByCurve",
        "Id": "799b4dce33ec4a2585187d988f7e267a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -22867.8842411053,
        "Y": -20500.6220741811
      }
    ],
    "Annotations": [
      {
        "Id": "295d1894ae1f4150a782003d9badc7d9",
        "Title": "Multiple creation methods exist for most Surfaces.  Surfaces, Polysurfaces (collections of Surfaces), and Nurbs Surfaces can be create by Points, Curves, and derived from other surfaces and solids",
        "Nodes": [],
        "Left": -23796.3802771348,
        "Top": -19714.316527622,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "1489336e40ab479baf26b60ff24b17db",
        "Title": "Tip:  Uncheck \"Preview Upstream\" in Right Click Menu to isolate Geometry in the node",
        "Nodes": [],
        "Left": -22419.3947083877,
        "Top": -19256.2494145129,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "cf263e4415014ac998550a75af5c7406",
        "Title": "Surfaces Joined as Polysurfaces can be evalued as a single entity",
        "Nodes": [],
        "Left": -22858.069373244,
        "Top": -19993.9113627357,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "690220821a204984bcfb78583354d477",
        "Title": "Geometry is not the same as a Revit Element:\r\nUse Import Instance To create Revit Imports from Surfaces and Solids in any Revit Environment, use Points and Curves to place Family Instances, or create Form in Mass and Generic Model By Point (Adaptive Component) Families",
        "Nodes": [],
        "Left": -22889.9191441972,
        "Top": -20411.205823341,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "283a0dbdc0684cbdbcac0503752aca10",
        "Title": "Edges, Points and other features can be derived from Surfaces using \"Actions\" appropriate to those geometries",
        "Nodes": [],
        "Left": -22841.8217572991,
        "Top": -19269.2985681732,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": 11370.475576651608,
    "Y": 9258.8939269095827,
    "Zoom": 0.44773099330677668
  }
}