{
  "Uuid": "3c9d0464-8643-5ffe-96e5-ab1769818209",
  "IsCustomNode": false,
  "Description": "",
  "Name": "Revit_GeometryCreation_Curves",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "918f7dc4e6d04d6b9b51c329d02db2b2",
      "Inputs": [
        {
          "Id": "7e4ecb613da44ca096e01392bc76cb9a",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "71d831bf6e164d7ba43a8a5e620956e9",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "643d9297ac474b36affa5bf4a97000ce",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "84830109d30f46f19ae4ee0abf993f6f",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "fb265a3222b04d2ab4f726b28bc90c10",
      "Inputs": [
        {
          "Id": "792a8e92696d4784ba634c5c58445feb",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2c87aff610e94f9fb20e0bb9a0f40e35",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "81f82d1becc84afda4aae302076ef4ed",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6b94b48be9fc4c8c851a52aa9565b0cf",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "e594468a412344b4870884b31915b703",
      "Inputs": [
        {
          "Id": "bc23b06d3147480693728d866bfd3102",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7b010d41d65a49e685d54a57366419ba",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0ccd412574e94dc6936d1649ffc21811",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d55937f018e744279d94882a59fb8409",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double",
      "Id": "64155f51080847f8be8d0fb57485b1e3",
      "Inputs": [
        {
          "Id": "c919e25fda2943c7bd5c704caa87cc90",
          "Name": "x",
          "Description": "X coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2d77c81d684845dcaea3eea68c1aa545",
          "Name": "y",
          "Description": "Y coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cfeaf1818800471a9fe122fd398d366e",
          "Name": "z",
          "Description": "Z coordinate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "fa1c20952f814e918726af8d7a24b380",
          "Name": "Point",
          "Description": "Point created by coordinates",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point given 3 cartesian coordinates\n\nPoint.ByCoordinates (x: double = 0, y: double = 0, z: double = 0): Point"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 10.0,
      "Id": "4f378cbb3c5d4496b11be74d16300d48",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "66423edb3392482abf506fb0b1a42da6",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 15.0,
      "Id": "e8e066b331a048adbf0fd5e0e27a1c20",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "2b4d785d54914443a0a4b0c7d29375f7",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.DoubleInput, CoreNodeModels",
      "NodeType": "NumberInputNode",
      "NumberType": "Double",
      "InputValue": 5.0,
      "Id": "bc1ea09916454e28b57419385b4d812b",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "9968220c1c844b169e48ccf6eac42f34",
          "Name": "",
          "Description": "Double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Creates a number."
    },
    {
      "ConcreteType": "CoreNodeModels.CreateList, CoreNodeModels",
      "VariableInputPorts": true,
      "NodeType": "ExtensionNode",
      "Id": "fc159a46e230462d91e7ac387a527d64",
      "Inputs": [
        {
          "Id": "c8862e8999b6408e9fb83b49aee89c81",
          "Name": "item0",
          "Description": "Item Index #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b936454956f84afcb7867ffb8c2a802a",
          "Name": "item1",
          "Description": "Item Index #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4a7cadcb642846ec90e5182218e07f60",
          "Name": "item2",
          "Description": "Item Index #2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b96b38b8a5cb4044b9a8c57b0d4249b0",
          "Name": "item3",
          "Description": "Item Index #3",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a1ad401e993b43cb8fa2496e74270a8f",
          "Name": "list",
          "Description": "A list",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Makes a new list out of the given inputs"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "7979f6ce63b64cfb98729d05812a111c",
      "Inputs": [
        {
          "Id": "4c0b08d86c4d4da588f9f239b69c99c7",
          "Name": "startPoint",
          "Description": "Line start point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "342125800dc54022ae6a8424e7dee0d2",
          "Name": "endPoint",
          "Description": "Line end point\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "bef7f3aa735746e2b0ef4c466c72bfd1",
          "Name": "Line",
          "Description": "Line from start and end point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "d200379e5c8c4f8b968d2f0887223d68",
      "Inputs": [
        {
          "Id": "609698e1619f46078fbb750b1d926960",
          "Name": "points",
          "Description": "Points for nurbs curve\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "72d79541a1fb4ee49ac85053f914fe10",
          "Name": "NurbsCurve",
          "Description": "Nurbscurve created from points",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by interpolating between points.\n\nNurbsCurve.ByPoints (points: Point[]): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[],bool",
      "Id": "835b1ec252ca4b639a1f2a0dde80b497",
      "Inputs": [
        {
          "Id": "048ff454c3374fcab7b871d07c3e04ff",
          "Name": "points",
          "Description": "Points to make polycurve\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e30de962998a472a91c08689973f18de",
          "Name": "connectLastToFirst",
          "Description": "True to connect last point to first point, false to leave open\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ca9bee947bd14dd892b213bec464fd0d",
          "Name": "PolyCurve",
          "Description": "Polycurve created by points",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Make PolyCurve by connecting points. Set the 'connectLastToFirst' input to true to close the PolyCurve.\n\nPolyCurve.ByPoints (points: Point[], connectLastToFirst: bool = false): PolyCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.Length",
      "Id": "eaae1aa1418848978ae4a743ac654a51",
      "Inputs": [
        {
          "Id": "81c2397aa6ea4052b24fa213262493a5",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "32b7029742eb4a77a324c63f1eb788c8",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns the total arc length of the curve\n\nCurve.Length: double"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.BoolSelector, CoreNodeModels",
      "NodeType": "BooleanInputNode",
      "InputValue": true,
      "Id": "6e4f5b2b2389451b95459dea13431b8b",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "f144a3b531ca4fbbb6d657c5b82159dc",
          "Name": "",
          "Description": "Boolean",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Selection between a true and false."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.NurbsCurve.ByControlPoints@Autodesk.DesignScript.Geometry.Point[],int,bool",
      "Id": "8ba3309a6ded4059a074fa0c2b291919",
      "Inputs": [
        {
          "Id": "bf9fb50678ac44aebbb9bd32cafa6887",
          "Name": "points",
          "Description": "Points for nurbs curve\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2bcfcb568a974392ab2d7ee0b8fd296f",
          "Name": "degree",
          "Description": "int\nDefault value : 3",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4a2381071b1541c8b27a188890efb64f",
          "Name": "closeCurve",
          "Description": "bool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "689da248fa3e452797be31dedccbb9b5",
          "Name": "NurbsCurve",
          "Description": "Nurbscurve created from points",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Create a BSplineCurve by using explicit control points. NOTE 1: BSplineCurves with deg=1 have G1 discontinuities, which cause problems for extrusion, sweep, and other operations. They should be avoided. Use a PolyCurve instead. NOTE 2: If the curve is periodic (closed), then the first and last points MUST be the same.\n\nNurbsCurve.ByControlPoints (points: Point[], degree: int = 3, closeCurve: bool = false): NurbsCurve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "2c8d0d140440438cb81cdcdeefc1b77e",
      "Inputs": [
        {
          "Id": "136d1188d65f450689f307ac78c13b9c",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7cbf19c2ba694767a68367f3999e2fef",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a275bbeb26bb407185a91f46d0d3af6b",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "0..1..#20;",
      "Id": "7820af5f481d4af79b359e608a64b96d",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "6fdede1d9c484cc68c374e6587b19347",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.ModelCurve.ByCurve@Autodesk.DesignScript.Geometry.Curve",
      "Id": "f4ef10a11aed49d5847439cdbdf5fea6",
      "Inputs": [
        {
          "Id": "1bdd3a63c00f4233a6d2499ee275950c",
          "Name": "curve",
          "Description": "Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "30b0aa4fee394e21a04f6e2ff7351ad8",
          "Name": "ModelCurve",
          "Description": "ModelCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Construct a Revit ModelCurve element from a Curve\n\nModelCurve.ByCurve (curve: Curve): ModelCurve"
    }
  ],
  "Connectors": [
    {
      "Start": "84830109d30f46f19ae4ee0abf993f6f",
      "End": "c8862e8999b6408e9fb83b49aee89c81",
      "Id": "93c4ce34c3244fddb513da92714e83de",
      "IsHidden": "False"
    },
    {
      "Start": "84830109d30f46f19ae4ee0abf993f6f",
      "End": "4c0b08d86c4d4da588f9f239b69c99c7",
      "Id": "dd4af268735e44d6800b6490c372df65",
      "IsHidden": "False"
    },
    {
      "Start": "6b94b48be9fc4c8c851a52aa9565b0cf",
      "End": "4a7cadcb642846ec90e5182218e07f60",
      "Id": "e38cb5ddb22248fcb85db0d84862f2a6",
      "IsHidden": "False"
    },
    {
      "Start": "d55937f018e744279d94882a59fb8409",
      "End": "b936454956f84afcb7867ffb8c2a802a",
      "Id": "53b9731bef1b4d54802f2a38f587678e",
      "IsHidden": "False"
    },
    {
      "Start": "d55937f018e744279d94882a59fb8409",
      "End": "342125800dc54022ae6a8424e7dee0d2",
      "Id": "759ee3e354664180b2523c6f3655af79",
      "IsHidden": "False"
    },
    {
      "Start": "fa1c20952f814e918726af8d7a24b380",
      "End": "b96b38b8a5cb4044b9a8c57b0d4249b0",
      "Id": "31758f6f490148fd9d7b7e4c7620e70d",
      "IsHidden": "False"
    },
    {
      "Start": "66423edb3392482abf506fb0b1a42da6",
      "End": "792a8e92696d4784ba634c5c58445feb",
      "Id": "deb923112a61429395579a3d41eb7212",
      "IsHidden": "False"
    },
    {
      "Start": "66423edb3392482abf506fb0b1a42da6",
      "End": "2c87aff610e94f9fb20e0bb9a0f40e35",
      "Id": "ce7784b9e7d74ee8afb3161f78974896",
      "IsHidden": "False"
    },
    {
      "Start": "2b4d785d54914443a0a4b0c7d29375f7",
      "End": "c919e25fda2943c7bd5c704caa87cc90",
      "Id": "4c7f0d4cc66940a3a5e5a96ae91ef086",
      "IsHidden": "False"
    },
    {
      "Start": "9968220c1c844b169e48ccf6eac42f34",
      "End": "7b010d41d65a49e685d54a57366419ba",
      "Id": "f3140d120b884ec6b8c09c25d6ad312c",
      "IsHidden": "False"
    },
    {
      "Start": "a1ad401e993b43cb8fa2496e74270a8f",
      "End": "609698e1619f46078fbb750b1d926960",
      "Id": "a953f7f494374541ba4c705ab6966fa9",
      "IsHidden": "False"
    },
    {
      "Start": "a1ad401e993b43cb8fa2496e74270a8f",
      "End": "048ff454c3374fcab7b871d07c3e04ff",
      "Id": "d241d3cff58642e1ada83840f9609113",
      "IsHidden": "False"
    },
    {
      "Start": "a1ad401e993b43cb8fa2496e74270a8f",
      "End": "bf9fb50678ac44aebbb9bd32cafa6887",
      "Id": "cfdda51d0318409f8f28a0d60131a0a7",
      "IsHidden": "False"
    },
    {
      "Start": "bef7f3aa735746e2b0ef4c466c72bfd1",
      "End": "81c2397aa6ea4052b24fa213262493a5",
      "Id": "6e28016e1b0c46948c5477a83c94228c",
      "IsHidden": "False"
    },
    {
      "Start": "72d79541a1fb4ee49ac85053f914fe10",
      "End": "1bdd3a63c00f4233a6d2499ee275950c",
      "Id": "d998dfab4d0a4250a7e2bc46acf348a7",
      "IsHidden": "False"
    },
    {
      "Start": "ca9bee947bd14dd892b213bec464fd0d",
      "End": "136d1188d65f450689f307ac78c13b9c",
      "Id": "eea8b9495d9842b7b7e93660dbd3880d",
      "IsHidden": "False"
    },
    {
      "Start": "f144a3b531ca4fbbb6d657c5b82159dc",
      "End": "4a2381071b1541c8b27a188890efb64f",
      "Id": "cf22c20d031c4eddaad5301957e47d5c",
      "IsHidden": "False"
    },
    {
      "Start": "6fdede1d9c484cc68c374e6587b19347",
      "End": "7cbf19c2ba694767a68367f3999e2fef",
      "Id": "e904aa1649164f9597d1064e15af073b",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Thumbnail": null,
  "GraphDocumentationURL": null,
  "ExtensionWorkspaceData": [
    {
      "ExtensionGuid": "28992e1d-abb9-417f-8b1b-05e053bee670",
      "Name": "Properties",
      "Version": "2.13",
      "Data": {}
    }
  ],
  "Author": "None provided",
  "Linting": {
    "activeLinter": "None",
    "activeLinterId": "7b75fb44-43fd-4631-a878-29f4d5d8399a",
    "warningCount": 0,
    "errorCount": 0
  },
  "Bindings": [
    {
      "NodeId": "f4ef10a1-1aed-49d5-8474-39cdbdf5fea6",
      "Binding": {
        "ByCurve_InClassDecl-1_InFunctionScope-1_Instance0_f4ef10a1-1aed-49d5-8474-39cdbdf5fea6": "PFNPQVAtRU5WOkVudmVsb3BlIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIHhtbG5zOnhzZD0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiIHhtbG5zOlNPQVAtRU5DPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VuY29kaW5nLyIgeG1sbnM6U09BUC1FTlY9Imh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3NvYXAvZW52ZWxvcGUvIiB4bWxuczpjbHI9Imh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vc29hcC9lbmNvZGluZy9jbHIvMS4wIiBTT0FQLUVOVjplbmNvZGluZ1N0eWxlPSJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy9zb2FwL2VuY29kaW5nLyI+DQo8U09BUC1FTlY6Qm9keT4NCjxhMTpDYWxsU2l0ZV94MDAyQl9UcmFjZVNlcmlhbGlzZXJIZWxwZXIgaWQ9InJlZi0xIiB4bWxuczphMT0iaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS9jbHIvbnNhc3NlbS9Qcm90b0NvcmUvUHJvdG9Db3JlJTJDJTIwVmVyc2lvbiUzRDIuMTMuMC4zMjcwJTJDJTIwQ3VsdHVyZSUzRG5ldXRyYWwlMkMlMjBQdWJsaWNLZXlUb2tlbiUzRG51bGwiPg0KPE51bWJlck9mRWxlbWVudHM+MTwvTnVtYmVyT2ZFbGVtZW50cz4NCjxCYXNlLTBfSGFzRGF0YT50cnVlPC9CYXNlLTBfSGFzRGF0YT4NCjxCYXNlLTBfRGF0YSBpZD0icmVmLTMiPlBGTlBRVkF0UlU1V09rVnVkbVZzYjNCbElIaHRiRzV6T25oemFUMGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TVM5WVRVeFRZMmhsYldFdGFXNXpkR0Z1WTJVaUlIaHRiRzV6T25oelpEMGlhSFIwY0RvdkwzZDNkeTUzTXk1dmNtY3ZNakF3TVM5WVRVeFRZMmhsYldFaUlIaHRiRzV6T2xOUFFWQXRSVTVEUFNKb2RIUndPaTh2YzJOb1pXMWhjeTU0Yld4emIyRndMbTl5Wnk5emIyRndMMlZ1WTI5a2FXNW5MeUlnZUcxc2JuTTZVMDlCVUMxRlRsWTlJbWgwZEhBNkx5OXpZMmhsYldGekxuaHRiSE52WVhBdWIzSm5MM052WVhBdlpXNTJaV3h2Y0dVdklpQjRiV3h1Y3pwamJISTlJbWgwZEhBNkx5OXpZMmhsYldGekxtMXBZM0p2YzI5bWRDNWpiMjB2YzI5aGNDOWxibU52WkdsdVp5OWpiSEl2TVM0d0lpQlRUMEZRTFVWT1ZqcGxibU52WkdsdVoxTjBlV3hsUFNKb2RIUndPaTh2YzJOb1pXMWhjeTU0Yld4emIyRndMbTl5Wnk5emIyRndMMlZ1WTI5a2FXNW5MeUkrRFFvOFUwOUJVQzFGVGxZNlFtOWtlVDROQ2p4aE1UcFRaWEpwWVd4cGVtRmliR1ZKWkNCcFpEMGljbVZtTFRFaUlIaHRiRzV6T21FeFBTSm9kSFJ3T2k4dmMyTm9aVzFoY3k1dGFXTnliM052Wm5RdVkyOXRMMk5zY2k5dWMyRnpjMlZ0TDFKbGRtbDBVMlZ5ZG1salpYTXVVR1Z5YzJsemRHVnVZMlV2VW1WMmFYUlRaWEoyYVdObGN5VXlReVV5TUZabGNuTnBiMjRsTTBReUxqRXpMakF1TXpJM01TVXlReVV5TUVOMWJIUjFjbVVsTTBSdVpYVjBjbUZzSlRKREpUSXdVSFZpYkdsalMyVjVWRzlyWlc0bE0wUnVkV3hzSWo0TkNqeHpkSEpwYm1kSlJDQnBaRDBpY21WbUxUTWlQakkzTW1OallXRmtMVEV4TWpBdE5HSTBNUzA0WXpnd0xUVTFNMkk0T0RZNU1ERXpOQzB3TURFd01qZzRaVHd2YzNSeWFXNW5TVVErRFFvOGFXNTBTVVErTVRBMU9EazFPRHd2YVc1MFNVUStEUW84TDJFeE9sTmxjbWxoYkdsNllXSnNaVWxrUGcwS1BDOVRUMEZRTFVWT1ZqcENiMlI1UGcwS1BDOVRUMEZRTFVWT1ZqcEZiblpsYkc5d1pUNE5DZz09PC9CYXNlLTBfRGF0YT4NCjxCYXNlLTBfSGFzTmVzdGVkRGF0YT5mYWxzZTwvQmFzZS0wX0hhc05lc3RlZERhdGE+DQo8L2ExOkNhbGxTaXRlX3gwMDJCX1RyYWNlU2VyaWFsaXNlckhlbHBlcj4NCjwvU09BUC1FTlY6Qm9keT4NCjwvU09BUC1FTlY6RW52ZWxvcGU+DQo="
      }
    }
  ],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.13.0.3270",
      "RunType": "Automatic",
      "RunPeriod": "100"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "918f7dc4e6d04d6b9b51c329d02db2b2",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24471.4286892823,
        "Y": -20038.7078255326
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "fb265a3222b04d2ab4f726b28bc90c10",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24471.4286892823,
        "Y": -19740.8597671717
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "e594468a412344b4870884b31915b703",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24470.1390765397,
        "Y": -19888.415696243
      },
      {
        "ShowGeometry": true,
        "Name": "Point.ByCoordinates",
        "Id": "64155f51080847f8be8d0fb57485b1e3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24469.5492826162,
        "Y": -19598.9498803032
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "4f378cbb3c5d4496b11be74d16300d48",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24609.192097963,
        "Y": -19704.0311350431
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "e8e066b331a048adbf0fd5e0e27a1c20",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24609.192097963,
        "Y": -19586.6763754658
      },
      {
        "ShowGeometry": true,
        "Name": "Number",
        "Id": "bc1ea09916454e28b57419385b4d812b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24609.192097963,
        "Y": -19857.4950514135
      },
      {
        "ShowGeometry": true,
        "Name": "List.Create",
        "Id": "fc159a46e230462d91e7ac387a527d64",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -24180.0283403342,
        "Y": -19861.4432371731
      },
      {
        "ShowGeometry": true,
        "Name": "Line.ByStartPointEndPoint",
        "Id": "7979f6ce63b64cfb98729d05812a111c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23755.1545802998,
        "Y": -20044.7180525039
      },
      {
        "ShowGeometry": true,
        "Name": "NurbsCurve.ByPoints",
        "Id": "d200379e5c8c4f8b968d2f0887223d68",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23753.2993692271,
        "Y": -19749.5634852303
      },
      {
        "ShowGeometry": true,
        "Name": "PolyCurve.ByPoints",
        "Id": "835b1ec252ca4b639a1f2a0dde80b497",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23758.4578201975,
        "Y": -19648.9736913069
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.Length",
        "Id": "eaae1aa1418848978ae4a743ac654a51",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23167.7427863276,
        "Y": -19987.0611419685
      },
      {
        "ShowGeometry": true,
        "Name": "Boolean",
        "Id": "6e4f5b2b2389451b95459dea13431b8b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23930.9783744459,
        "Y": -19851.6236889259
      },
      {
        "ShowGeometry": true,
        "Name": "NurbsCurve.ByControlPoints",
        "Id": "8ba3309a6ded4059a074fa0c2b291919",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23754.5915986248,
        "Y": -19921.0404200555
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.PointAtParameter",
        "Id": "2c8d0d140440438cb81cdcdeefc1b77e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23180.3194152019,
        "Y": -19793.7458270855
      },
      {
        "ShowGeometry": true,
        "Name": "Code Block",
        "Id": "7820af5f481d4af79b359e608a64b96d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23325.7070393249,
        "Y": -19700.2562560531
      },
      {
        "ShowGeometry": true,
        "Name": "ModelCurve.ByCurve",
        "Id": "f4ef10a11aed49d5847439cdbdf5fea6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -23201.683049685194,
        "Y": -19540.606011735919
      }
    ],
    "Annotations": [
      {
        "Id": "1c567ac9581049f59bc06b2c100c053a",
        "Title": "Curves, Polycurves (collections of Curves), Nurbs, and Lines all derive from \"Curves\", and so all Curve \"Actions\" and \"Queries\" can be done to all of them",
        "DescriptionText": null,
        "IsExpanded": true,
        "WidthAdjustment": 0.0,
        "HeightAdjustment": 0.0,
        "Nodes": [],
        "HasNestedGroups": false,
        "Left": -23240.3161700635,
        "Top": -19873.7297569865,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "724635231cea4135b320176e240209a5",
        "Title": "Multiple creation methods exist for most curves.  ",
        "DescriptionText": null,
        "IsExpanded": true,
        "WidthAdjustment": 0.0,
        "HeightAdjustment": 0.0,
        "Nodes": [],
        "HasNestedGroups": false,
        "Left": -23755.3612463271,
        "Top": -20085.2107041965,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "6d21a2a5a44848f2a110aec8699a34ff",
        "Title": "Pass any curve element to Revit Elements that are driven by Lines or other Curves to create them",
        "DescriptionText": null,
        "IsExpanded": true,
        "WidthAdjustment": 0.0,
        "HeightAdjustment": 0.0,
        "Nodes": [],
        "HasNestedGroups": false,
        "Left": -23230.477265241,
        "Top": -19597.6691441897,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": 16502.259384473706,
    "Y": 13850.073918995129,
    "Zoom": 0.68793184622315484
  }
}