<Workspace Version="1.0.0.832" X="-1595.88140541157" Y="105.599856410285" zoom="1.09871222902565" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Autodesk.DesignScript.Geometry.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Sphere" resolvedName="Autodesk.DesignScript.Geometry.Sphere" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="DSCore.Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
    <ClassMap partialName="Display" resolvedName="Display.Display" assemblyName="Display.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="acedb6a7-7d32-4894-8b3c-727af2e58d79" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1553.34351229575" y="63.5074342979784" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="def BlueSphere()&#xA;{&#xA;point1 = Autodesk.Point.ByCoordinates(40, 0, 0);&#xA;sphere1 = Sphere.ByCenterPointRadius(point1, 8);&#xA;color1 = DSCore.Color.ByARGB(255, 0, 0, 255);&#xA;return = Display.ByGeometryColor(sphere1, color1);&#xA;};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="be36aaa4-5119-4e6c-a4a1-31c959ed0b76" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2031.71326275676" y="103.236016641297" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="BlueSphere();" ShouldFocus="false" />
    <CoreNodeModels.Watch guid="dc46358c-d71e-4764-9113-c7bc0dae8909" type="CoreNodeModels.Watch" nickname="Watch" x="2261.63078899667" y="53.153266202839" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="2610cf91-b2b2-4ba7-a92b-c675a0d17d05" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1560.37858231151" y="267.359033163985" isVisible="false" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="def RedPoints()&#xA;{&#xA;points = Autodesk.Point.ByCoordinates(1..5, 0, 0);&#xA;color1 = DSCore.Color.ByARGB(255, 255, 0, 0);&#xA;return = Display.ByGeometryColor(points, color1);&#xA;};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="c2d81800-6147-4e66-a215-9eb1a7ba2426" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="2033.71874855976" y="290.425776389197" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="RedPoints();" ShouldFocus="false" />
    <CoreNodeModels.Watch guid="79bc4023-4f01-4b11-823e-75e615ad534c" type="CoreNodeModels.Watch" nickname="Watch" x="2266.18157114682" y="262.489245109678" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="be36aaa4-5119-4e6c-a4a1-31c959ed0b76" start_index="0" end="dc46358c-d71e-4764-9113-c7bc0dae8909" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="c2d81800-6147-4e66-a215-9eb1a7ba2426" start_index="0" end="79bc4023-4f01-4b11-823e-75e615ad534c" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="2.09484386444092" eyeY="20.8824100494385" eyeZ="51.4053955078125" lookX="-7.09484386444092" lookY="-9.88241004943848" lookZ="-59.4053955078125" upX="0.0062064272351563" upY="0.998629510402679" upZ="0.0519666485488415" />
  </Cameras>
</Workspace>