<Workspace Version="0.7.0.21043" X="3.00244529758953" Y="-87.38750331179" zoom="0.816855683253462" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.Watch3D type="Dynamo.Nodes.Watch3D" guid="649d514a-3f76-4426-9e2b-0f4e09dfbefc" nickname="Watch 3D" x="1214.3091933215" y="201.659816903587" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <view width="210" height="257">
        <camera pos_x="20.6975697527233" pos_y="20.6975697527233" pos_z="20.6965697527233" look_x="-20.6975697527233" look_y="-20.6975697527233" look_z="-20.6975697527233" />
      </view>
    </Dynamo.Nodes.Watch3D>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="8a7c1673-cdd9-4ec2-a589-0c6610d58bc8" nickname="Point.ByCoordinates" x="477.412947005221" y="530.920962063862" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double" />
    <Dynamo.Nodes.DoubleSlider type="Dynamo.Nodes.DoubleSlider" guid="33d71146-f2e3-437a-a779-0a658e020a54" nickname="Number Slider" x="45.896491278553" y="481.738716921468" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double>25.97</System.Double>
      <Range min="0" max="30" />
    </Dynamo.Nodes.DoubleSlider>
    <Dynamo.Nodes.DoubleSlider type="Dynamo.Nodes.DoubleSlider" guid="286b8651-374e-44a9-a8c8-12e30046ded4" nickname="Number Slider" x="44.646491278553" y="546.738716921468" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double>19.925</System.Double>
      <Range min="0" max="30" />
    </Dynamo.Nodes.DoubleSlider>
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="9d60a94c-fa1e-4907-81d9-929e8faf9335" nickname="Code Block" x="329.959834289504" y="616.769850801057" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="54b611fb-af65-4693-9b87-bbff25e00cc0" nickname="Circle.ByCenterPointRadius" x="1033.84885621683" y="202.830404819838" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double" />
    <Dynamo.Nodes.DoubleSlider type="Dynamo.Nodes.DoubleSlider" guid="d3ec75e7-ed86-47c5-b885-d35099716698" nickname="Number Slider" x="683.757478726179" y="295.947058835454" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double>0.939</System.Double>
      <Range min="0.1" max="2" />
    </Dynamo.Nodes.DoubleSlider>
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="59cc7f97-6b75-4147-ae08-2e22bc67ee69" nickname="Watch" x="602.090812059513" y="529.280392168788" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="39ef32cd-351b-4409-948e-a1c9486ccb76" nickname="Code Block" x="133" y="234" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..30..#15;&#xA;0;" ShouldFocus="false" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="c4c33e83-7c8e-4674-afc4-47ae426d78d2" nickname="Point.ByCoordinates" x="322.540459571705" y="234.849806713729" isVisible="false" isUpstreamVisible="true" lacing="CrossProduct" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Nodes.DSFunction>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="a10cedb9-12df-49ef-b862-3681c694fee3" nickname="/" x="669.343514470368" y="867.708085945088" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="" function="/@," />
    <Dynamo.Nodes.DoubleInput type="Dynamo.Nodes.DoubleInput" guid="79858eeb-6b04-42eb-9b69-6530ded3820f" nickname="Number" x="552.231565860092" y="936.403492083584" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double value="30" />
    </Dynamo.Nodes.DoubleInput>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="1eb2bfac-4c78-4f3a-94b5-64de45436349" nickname="Geometry.DistanceTo" x="497.155147937498" y="819.716165976394" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Geometry.DistanceTo@Autodesk.DesignScript.Geometry.Geometry" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="f5e95627-7970-4490-b5b6-2d16a557d5ba" nickname="ModelCurve.ReferenceCurveByCurve" x="1250.27754082712" y="822.863421833083" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\RevitNodes.dll" function="Revit.Elements.ModelCurve.ReferenceCurveByCurve@Autodesk.DesignScript.Geometry.Curve" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="8a7c1673-cdd9-4ec2-a589-0c6610d58bc8" start_index="0" end="59cc7f97-6b75-4147-ae08-2e22bc67ee69" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="33d71146-f2e3-437a-a779-0a658e020a54" start_index="0" end="8a7c1673-cdd9-4ec2-a589-0c6610d58bc8" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="286b8651-374e-44a9-a8c8-12e30046ded4" start_index="0" end="8a7c1673-cdd9-4ec2-a589-0c6610d58bc8" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="9d60a94c-fa1e-4907-81d9-929e8faf9335" start_index="0" end="8a7c1673-cdd9-4ec2-a589-0c6610d58bc8" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="54b611fb-af65-4693-9b87-bbff25e00cc0" start_index="0" end="649d514a-3f76-4426-9e2b-0f4e09dfbefc" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d3ec75e7-ed86-47c5-b885-d35099716698" start_index="0" end="54b611fb-af65-4693-9b87-bbff25e00cc0" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="39ef32cd-351b-4409-948e-a1c9486ccb76" start_index="0" end="c4c33e83-7c8e-4674-afc4-47ae426d78d2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="39ef32cd-351b-4409-948e-a1c9486ccb76" start_index="0" end="c4c33e83-7c8e-4674-afc4-47ae426d78d2" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="39ef32cd-351b-4409-948e-a1c9486ccb76" start_index="1" end="c4c33e83-7c8e-4674-afc4-47ae426d78d2" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="c4c33e83-7c8e-4674-afc4-47ae426d78d2" start_index="0" end="54b611fb-af65-4693-9b87-bbff25e00cc0" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="79858eeb-6b04-42eb-9b69-6530ded3820f" start_index="0" end="a10cedb9-12df-49ef-b862-3681c694fee3" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="XYZ Point Grid" x="336.765338285622" y="191.317004714217" />
    <Dynamo.Models.NoteModel text="'Attractor' Point" x="471.924009795694" y="486.377779025378" />
    <Dynamo.Models.NoteModel text="Circle with variable radii" x="1020.29806041525" y="158.930549912172" />
    <Dynamo.Models.NoteModel text="Create a distance-based &#xD;&#xA;relationship with a single point." x="498.088646546355" y="759.038756400655" />
    <Dynamo.Models.NoteModel text="Make Revit Stuff" x="1253.36468428314" y="776.603096891086" />
  </Notes>
</Workspace>