<Workspace Version="1.0.1.1743" X="32.914580178806" Y="-15.3929046278543" zoom="0.915597835894024" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ec7e9403-3631-4d80-b74a-0fc90574fbfe" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="-12.2237572554777" y="158" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="p1 = Point.ByCoordinates(00,0,0);" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="ed84faf2-ec5a-4ba2-93c4-2ded4ef274bd" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="187.776242744522" y="234.473236011279" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="5;&#xA;0;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="36271dd1-f134-4c17-ae52-be744764a1c2" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Circle.ByCenterPointRadius" x="358.018991066993" y="181.462442370589" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="ec7e9403-3631-4d80-b74a-0fc90574fbfe" start_index="0" end="36271dd1-f134-4c17-ae52-be744764a1c2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="ed84faf2-ec5a-4ba2-93c4-2ded4ef274bd" start_index="0" end="36271dd1-f134-4c17-ae52-be744764a1c2" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>