<Workspace Version="1.0.1.1743" X="-274.375650304597" Y="-1357.17717517809" zoom="1.17260257552697" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="False">
  <NamespaceResolutionMap>
    <ClassMap partialName="Arc" resolvedName="Autodesk.DesignScript.Geometry.Arc" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="NurbsCurve" resolvedName="Autodesk.DesignScript.Geometry.NurbsCurve" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Line" resolvedName="Autodesk.DesignScript.Geometry.Line" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Curve" resolvedName="Autodesk.DesignScript.Geometry.Curve" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="fe37af5c-d4e7-4fc5-9f27-8b5c7a450ffa" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="288" y="1214" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="point1          = Point.ByCoordinates(0, 0, 0);&#xA;point2          = Point.ByCoordinates(10, 0, 0);&#xA;centerPoint     = Point.ByCoordinates(9, 6, 0);&#xA;myArc           = Arc.ByCenterPointRadiusAngle(centerPoint, 3, -90, 180, Vector.ByCoordinates(0, 0, 1));&#xA;arrayOfPoints   = { point1, point1.Translate(3, 3, 0), point1.Translate(6, 0, 0), point1.Translate(9, 3, 0) };&#xA;mySpline        = NurbsCurve.ByPoints(arrayOfPoints);&#xA;startPoint1     = myArc.EndPoint;&#xA;myLine1         = Line.ByStartPointDirectionLength(&#xA;                                startPoint1, Vector.ByCoordinates(-1, 0, 0),9);&#xA;startPoint2     = myLine1.EndPoint;&#xA;myLine2         = Line.ByStartPointDirectionLength(startPoint2, Vector.ByCoordinates(0, -1, 0),9);&#xA;&#xA;arrayCurve = {myArc, mySpline, myLine1, myLine2};" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="6156debc-13ac-4b29-abae-7096f97a6cba" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1035" y="1373" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="compositeCurve = Curve.Composite(arayCurve);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fe37af5c-d4e7-4fc5-9f27-8b5c7a450ffa" start_index="10" end="6156debc-13ac-4b29-abae-7096f97a6cba" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>