<Workspace Version="2.0.0.4093" X="58.3977693099254" Y="173.560914792667" zoom="1.17131835730765" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap>
    <ClassMap partialName="CoordinateSystem" resolvedName="Autodesk.DesignScript.Geometry.CoordinateSystem" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Cylinder" resolvedName="Autodesk.DesignScript.Geometry.Cylinder" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Cuboid" resolvedName="Autodesk.DesignScript.Geometry.Cuboid" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Solid" resolvedName="Autodesk.DesignScript.Geometry.Solid" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="532f8b75-4957-460e-bfff-8247f285e14a" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1.8595621133635" y="77.5603572279534" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="WCS = CoordinateSystem.Identity();&#xA;&#xA;//======Establish the context for creating Solid================&#xA;firstSolid      = Cylinder.ByRadiusHeight(&#xA;    CoordinateSystem.Translate(WCS, 15, 15, 0), 2.5, 50);&#xA;ArrayOfSolids   =&#xA;{&#xA;    firstSolid,&#xA;    Solid.Translate(firstSolid, -30, 0, 0),&#xA;    Solid.Translate(firstSolid, -30, -30, 0),&#xA;    Solid.Translate(firstSolid, 0, -30, 0)&#xA;};&#xA;secondSolid     = Cuboid.ByLengths(WCS, 30, 30, 30);" ShouldFocus="false">
      <OutPortInfo LineIndex="0" />
      <OutPortInfo LineIndex="3" />
      <OutPortInfo LineIndex="5" />
      <OutPortInfo LineIndex="12" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="824707aa-3c5f-4fc3-a183-a21ff7804932" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Union" x="707.698954775303" y="121.592429832398" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Union@Autodesk.DesignScript.Geometry.Solid">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0ef5c7c7-4fa5-4542-a6bc-b45a041bf9f6" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.Union" x="736.78235049822" y="320.667755523291" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.Union@Autodesk.DesignScript.Geometry.Solid">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="532f8b75-4957-460e-bfff-8247f285e14a" start_index="1" end="0ef5c7c7-4fa5-4542-a6bc-b45a041bf9f6" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="532f8b75-4957-460e-bfff-8247f285e14a" start_index="2" end="824707aa-3c5f-4fc3-a183-a21ff7804932" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="532f8b75-4957-460e-bfff-8247f285e14a" start_index="3" end="824707aa-3c5f-4fc3-a183-a21ff7804932" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="532f8b75-4957-460e-bfff-8247f285e14a" start_index="3" end="0ef5c7c7-4fa5-4542-a6bc-b45a041bf9f6" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="a6a2e4dd-d530-4567-946c-4268d325cea8" text="Input single solid, Union is working." x="720.664974838382" y="404.208222723656" />
    <Dynamo.Graph.Notes.NoteModel guid="36f3375b-0e7c-4ff0-ba8d-2e72dabab62b" text="Input ArrayOfSolids, Union failed." x="710.296042555358" y="66.6418717318969" />
  </Notes>
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>