<Commands ExitAfterPlayback="true" PauseAfterPlaybackInMs="10" CommandIntervalInMs="20">
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <CreateNodeCommand NodeId="433186e8-5e26-4837-be3a-3329b0c6011d" NodeName="Code Block" X="270" Y="176" DefaultPosition="false" TransformCoordinates="true" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <UpdateModelValueCommand ModelGuid="433186e8-5e26-4837-be3a-3329b0c6011d" Name="Code" Value="Point.ByCoordinates(x,0,0);" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <SelectInRegionCommand X="580" Y="244" Width="0" Height="1" IsCrossSelection="false" />
  <CreateNodeCommand NodeId="c38786e1-62ea-4413-96ac-5e63cba7c7fa" NodeName="Code Block" X="580" Y="244" DefaultPosition="false" TransformCoordinates="true" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <UpdateModelValueCommand ModelGuid="c38786e1-62ea-4413-96ac-5e63cba7c7fa" Name="Code" Value="10" />
  <SelectModelCommand ModelGuid="c38786e1-62ea-4413-96ac-5e63cba7c7fa" Modifiers="0" />
  <DragSelectionCommand X="522" Y="236" DragOperation="0" />
  <DragSelectionCommand X="89" Y="172" DragOperation="1" />
  <MakeConnectionCommand NodeId="c38786e1-62ea-4413-96ac-5e63cba7c7fa" PortIndex="0" Type="1" ConnectionMode="0" />
  <MakeConnectionCommand NodeId="433186e8-5e26-4837-be3a-3329b0c6011d" PortIndex="0" Type="0" ConnectionMode="1" />
  <CreateNodeCommand NodeId="d6f7a52b-b5a9-48fb-b83b-ea27804b21f8" NodeName="Autodesk.DesignScript.Geometry.Point.X" X="0" Y="0" DefaultPosition="true" TransformCoordinates="true" />
  <SelectModelCommand ModelGuid="d6f7a52b-b5a9-48fb-b83b-ea27804b21f8" Modifiers="0" />
  <DragSelectionCommand X="437" Y="219" DragOperation="0" />
  <DragSelectionCommand X="657" Y="184" DragOperation="1" />
  <MakeConnectionCommand NodeId="433186e8-5e26-4837-be3a-3329b0c6011d" PortIndex="0" Type="1" ConnectionMode="0" />
  <MakeConnectionCommand NodeId="d6f7a52b-b5a9-48fb-b83b-ea27804b21f8" PortIndex="0" Type="0" ConnectionMode="1" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
  <SelectModelCommand ModelGuid="d6f7a52b-b5a9-48fb-b83b-ea27804b21f8" Modifiers="0" />
  <UpdateModelValueCommand ModelGuid="c38786e1-62ea-4413-96ac-5e63cba7c7fa" Name="Code" Value="5;" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
  <UpdateModelValueCommand ModelGuid="433186e8-5e26-4837-be3a-3329b0c6011d" Name="Code" Value="Point.ByCoordinates(10,0,0);" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
  <UpdateModelValueCommand ModelGuid="433186e8-5e26-4837-be3a-3329b0c6011d" Name="Code" Value="Point.ByCoordinates(10,0,0);" />
  <SelectModelCommand ModelGuid="433186e8-5e26-4837-be3a-3329b0c6011d" Modifiers="0" />
  <DragSelectionCommand X="358" Y="166" DragOperation="0" />
  <DragSelectionCommand X="358" Y="166" DragOperation="1" />
  <UpdateModelValueCommand ModelGuid="433186e8-5e26-4837-be3a-3329b0c6011d" Name="Code" Value="Point.ByCoordinates(-5,0,0);" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
</Commands>