<Commands ExitAfterPlayback="true" PauseAfterPlaybackInMs="10" CommandIntervalInMs="20">
  <CreateNodeCommand NodeId="9f367153-89e7-4785-af78-a1bcc41ec394" NodeName="Python Script" X="0" Y="0" DefaultPosition="true" TransformCoordinates="true" />
  <ModelEventCommand ModelGuid="9f367153-89e7-4785-af78-a1bcc41ec394" EventName="AddInPort" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <CreateNodeCommand NodeId="34d7b885-db18-496c-ac9c-fbcb8370560c" NodeName="Code Block" X="177" Y="248" DefaultPosition="false" TransformCoordinates="true" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <UpdateModelValueCommand ModelGuid="34d7b885-db18-496c-ac9c-fbcb8370560c" Name="Code" Value="1" />
  <MakeConnectionCommand NodeId="34d7b885-db18-496c-ac9c-fbcb8370560c" PortIndex="0" Type="1" ConnectionMode="0" />
  <MakeConnectionCommand NodeId="9f367153-89e7-4785-af78-a1bcc41ec394" PortIndex="0" Type="0" ConnectionMode="1" />
  <UpdateModelValueCommand ModelGuid="9f367153-89e7-4785-af78-a1bcc41ec394" Name="ScriptContent" Value="import clr&#xA;clr.AddReference('ProtoGeometry')&#xA;from Autodesk.DesignScript.Geometry import *&#xA;#The inputs to this node will be stored as a list in the IN variable.&#xA;dataEnteringNode = IN&#xA;&#xA;#Assign your output to the OUT variable&#xA;OUT = IN" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
</Commands>