<Commands ExitAfterPlayback="true" PauseAfterPlaybackInMs="10" CommandIntervalInMs="20">
  <CreateNodeCommand NodeId="93eaf7f1-0328-450b-8d40-61cf9a73f047" NodeName="Python Script" X="0" Y="0" DefaultPosition="true" TransformCoordinates="true" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <CreateNodeCommand NodeId="6b032135-e882-4a2b-9c23-83d643e6e441" NodeName="Code Block" X="174" Y="246" DefaultPosition="false" TransformCoordinates="true" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <UpdateModelValueCommand ModelGuid="6b032135-e882-4a2b-9c23-83d643e6e441" Name="Code" Value="1" />
  <MakeConnectionCommand NodeId="6b032135-e882-4a2b-9c23-83d643e6e441" PortIndex="0" Type="1" ConnectionMode="0" />
  <ModelEventCommand ModelGuid="93eaf7f1-0328-450b-8d40-61cf9a73f047" EventName="AddInPort" />
  <MakeConnectionCommand NodeId="93eaf7f1-0328-450b-8d40-61cf9a73f047" PortIndex="0" Type="0" ConnectionMode="1" />
  <UpdateModelValueCommand ModelGuid="93eaf7f1-0328-450b-8d40-61cf9a73f047" Name="ScriptContent" Value="import clr&#xA;clr.AddReference('ProtoGeometry')&#xA;from Autodesk.DesignScript.Geometry import *&#xA;#The inputs to this node will be stored as a list in the IN variable.&#xA;dataEnteringNode = IN&#xA;a=IN&#xA;#Assign your output to the OUT variable&#xA;OUT = a" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
  <UndoRedoCommand CmdOperation="0" />
  <UndoRedoCommand CmdOperation="0" />
  <UndoRedoCommand CmdOperation="0" />
  <UndoRedoCommand CmdOperation="0" />
  <UndoRedoCommand CmdOperation="0" />
  <UndoRedoCommand CmdOperation="1" />
  <UndoRedoCommand CmdOperation="1" />
  <UndoRedoCommand CmdOperation="1" />
  <UndoRedoCommand CmdOperation="1" />
  <UndoRedoCommand CmdOperation="1" />
  <RunCancelCommand ShowErrors="false" CancelRun="false" />
  <SelectModelCommand ModelGuid="00000000-0000-0000-0000-000000000000" Modifiers="0" />
</Commands>