<Workspace Version="1.0.1.1580" X="0" Y="0" zoom="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3d99f2de-7750-4517-852a-bf5ed28a0573" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Cuboid.ByLengths" x="401.5" y="352" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Cuboid.ByLengths@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="3ad9af9f-cfa7-4863-a9bd-21545c03900b" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Sphere.ByCenterPointRadius" x="401.5" y="512" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius@Autodesk.DesignScript.Geometry.Point,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="9f2ea7e8-51e8-4361-a337-9f7849a00d29" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.UnionAll" x="911.5" y="352" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.UnionAll@Autodesk.DesignScript.Geometry.Solid[]" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ec6a82c4-ee31-4c72-a5ef-58dc1bec0fe9" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Solid.ByUnion" x="911.5" y="486" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Solid.ByUnion@Autodesk.DesignScript.Geometry.Solid[]" />
    <CoreNodeModels.CreateList guid="cb7e0ca6-1e68-4368-999e-a9ae490e03a5" type="CoreNodeModels.CreateList" nickname="List.Create" x="691.5" y="486" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2" />
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="3834ec6d-2af2-4ec8-bbf7-b55a09352e0e" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="222.5" y="408.213333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="10;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="3d99f2de-7750-4517-852a-bf5ed28a0573" start_index="0" end="cb7e0ca6-1e68-4368-999e-a9ae490e03a5" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3d99f2de-7750-4517-852a-bf5ed28a0573" start_index="0" end="9f2ea7e8-51e8-4361-a337-9f7849a00d29" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ad9af9f-cfa7-4863-a9bd-21545c03900b" start_index="0" end="cb7e0ca6-1e68-4368-999e-a9ae490e03a5" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3ad9af9f-cfa7-4863-a9bd-21545c03900b" start_index="0" end="9f2ea7e8-51e8-4361-a337-9f7849a00d29" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="cb7e0ca6-1e68-4368-999e-a9ae490e03a5" start_index="0" end="ec6a82c4-ee31-4c72-a5ef-58dc1bec0fe9" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3834ec6d-2af2-4ec8-bbf7-b55a09352e0e" start_index="0" end="3d99f2de-7750-4517-852a-bf5ed28a0573" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>