<Workspace Version="0.6.2.14024" X="-4.36904761904702" Y="115.952380952381" zoom="1" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.PointBySelection type="Dynamo.Nodes.PointBySelection" guid="8632dddf-d923-4cfa-b128-2fed136507d3" nickname="Select Reference Point" x="85.0000000000001" y="10.8" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="59b81eea-9ba3-46cc-b901-a8a7773923bb-00008285" />
    </Dynamo.Nodes.PointBySelection>
    <Dynamo.Nodes.NewList type="Dynamo.Nodes.NewList" guid="d0479c19-2cc3-4765-9c48-4c8dc300a271" nickname="List" x="261.95" y="44.15" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Input name="index0" />
      <Input name="index1" />
    </Dynamo.Nodes.NewList>
    <Dynamo.Nodes.PointBySelection type="Dynamo.Nodes.PointBySelection" guid="5a6e0f00-c9be-41a9-8d6f-931b304d5f3b" nickname="Select Reference Point" x="86.7500000000001" y="104.75" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <instance id="59b81eea-9ba3-46cc-b901-a8a7773923bb-000082c0" />
    </Dynamo.Nodes.PointBySelection>
    <Dynamo.Nodes.Python type="Dynamo.Nodes.Python" guid="c925d90d-be67-4567-a496-74f203e8ed2a" nickname="Python Script" x="464.501162790698" y="58" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <Script>#derived from Nathan Miller's example http://theprovingground.wikidot.com/revit-api-py-curves

# Default imports
import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
import Autodesk
import sys
import clr
path = r'C:\Autodesk\Dynamo\Core'
exec_path = r'C:\Users\Ian\Documents\GitHub\Dynamo\bin\AnyCPU\Debug'
sys.path.append(path)
sys.path.append(exec_path)
clr.AddReference('LibGNet')
from Autodesk.LibG import *
import math

doc = __revit__.ActiveUIDocument.Document
app = __revit__.Application

# get the input points
beginPoint = IN[0]
endPoint = IN[1]

# The __persistent__ dictionary gives you a persistent
# dictionary between runs.  Here we use it to store elements
# we wish to clean up later.

# Initialize if it's not already created.
if 'oldElements' not in __persistent__:
	__persistent__['oldElements'] = []

#delete old elements
if __persistent__['oldElements'].Count &gt; 0:
     count = 0
     for eID in __persistent__['oldElements']:
          doc.Delete( __persistent__['oldElements'][count] )
          count = count + 1

# Clear the dictionary as we've deleted those old elements
__persistent__['oldElements'] = []

lineRefPointArray = ReferencePointArray()
lineRefPointArray.Append(beginPoint)
lineRefPointArray.Append(endPoint)

crv = doc.FamilyCreate.NewCurveByPoints(lineRefPointArray)
crvRef = crv.GeometryCurve
refptarr = ReferencePointArray()

#use for loop to create a series of points
steps = 20
for i in range(0,steps+1):
    pt = crvRef.Evaluate(float(i)/steps,1) # returns and XYZ
    x = pt.X
    y = pt.Y
    z = pt.Z + math.sin(i)*steps 
    myXYZ = XYZ(x,y,z)
    refPt = doc.FamilyCreate.NewReferencePoint(myXYZ)
    __persistent__['oldElements'].Add(refPt.Id)
    refptarr.Append(refPt)
</Script>
    </Dynamo.Nodes.Python>
    <Dynamo.Nodes.Transaction type="Dynamo.Nodes.Transaction" guid="1dbc8f31-adf2-4f09-b8a7-28e4e4a10ac6" nickname="Transaction" x="645.826176494656" y="69.7722865974853" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
    <Dynamo.Nodes.Watch type="Dynamo.Nodes.Watch" guid="09733fa5-d8c0-4005-81c3-6b092175cc6f" nickname="Watch" x="746.369047619047" y="229.047619047619" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="8632dddf-d923-4cfa-b128-2fed136507d3" start_index="0" end="d0479c19-2cc3-4765-9c48-4c8dc300a271" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="d0479c19-2cc3-4765-9c48-4c8dc300a271" start_index="0" end="c925d90d-be67-4567-a496-74f203e8ed2a" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="5a6e0f00-c9be-41a9-8d6f-931b304d5f3b" start_index="0" end="d0479c19-2cc3-4765-9c48-4c8dc300a271" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="c925d90d-be67-4567-a496-74f203e8ed2a" start_index="0" end="1dbc8f31-adf2-4f09-b8a7-28e4e4a10ac6" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="c925d90d-be67-4567-a496-74f203e8ed2a" start_index="0" end="09733fa5-d8c0-4005-81c3-6b092175cc6f" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Create a transaction to wrap the python script." x="576.833333333333" y="12.4166666666666" />
    <Dynamo.Models.NoteModel text="Select two points." x="84" y="200" />
    <Dynamo.Models.NoteModel text="Create a list." x="282" y="147" />
    <Dynamo.Models.NoteModel text="Make a python script." x="456" y="139" />
  </Notes>
</Workspace>