<Workspace Version="1.3.0.875" X="0" Y="0" zoom="1" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="07ac48ce-beda-447c-aa17-47cdfde5a7d6" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="124" y="177" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="2;" ShouldFocus="false" />
    <Dynamo.Graph.Nodes.CustomNodes.Function guid="2d2e2b6c-fce8-4a23-9bf0-98b441fe78c2" type="Dynamo.Graph.Nodes.CustomNodes.Function" nickname="Point" x="270" y="223" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <ID value="cb0bf3fc-e511-402e-a12e-775b8d18bf77" />
      <Name value="Point" />
      <Description value="" />
      <Inputs>
        <Input value="x" />
      </Inputs>
      <Outputs>
        <Output value="out" />
      </Outputs>
    </Dynamo.Graph.Nodes.CustomNodes.Function>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="5ed80f52-ea60-4a07-8dd0-514f0eb70a28" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.X" x="478" y="177" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.X">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="07ac48ce-beda-447c-aa17-47cdfde5a7d6" start_index="0" end="2d2e2b6c-fce8-4a23-9bf0-98b441fe78c2" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="2d2e2b6c-fce8-4a23-9bf0-98b441fe78c2" start_index="0" end="5ed80f52-ea60-4a07-8dd0-514f0eb70a28" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>