<Workspace Version="0.7.0.18969" X="-135.467986069671" Y="-175.026414405667" zoom="1.50237217924567" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DoubleSlider type="Dynamo.Nodes.DoubleSlider" guid="a1844c0d-99bd-4a32-84f8-2e94685f3229" nickname="Number Slider" x="-255.090712742981" y="186.319114470842" isVisible="true" isUpstreamVisible="true" lacing="Disabled">
      <System.Double>33.333</System.Double>
      <Range min="0" max="100" />
    </Dynamo.Nodes.DoubleSlider>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="7e23ea22-600f-4263-89af-defa541e90f2" nickname="ReferencePoint.ByPoint" x="616.799136739771" y="101.244013709725" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="..\..\RevitNodes.dll" function="Revit.Elements.ReferencePoint.ByPoint@Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="6e9a64fa-8937-4cea-95fc-bd52aaf3404a" nickname="CurveElement.Curve" x="203.586846097514" y="68.7416719484366" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\RevitNodes.dll" function="Revit.Elements.CurveElement.Curve" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="ca773327-cc3f-4922-af32-e48076fa47e3" nickname="Curve.PointAtParameter" x="419.063741936948" y="101.244013709725" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="315c8e1c-c741-40dc-9636-56d19a140896" nickname="Code Block" x="233.586846097514" y="182.559968084746" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..1..#x;" ShouldFocus="false" />
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="92552ee0-bf78-48ad-9f66-97291b175a48" nickname="Select Model Element" x="-66.0907127429806" y="49.903086153108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="a1844c0d-99bd-4a32-84f8-2e94685f3229" start_index="0" end="315c8e1c-c741-40dc-9636-56d19a140896" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="6e9a64fa-8937-4cea-95fc-bd52aaf3404a" start_index="0" end="ca773327-cc3f-4922-af32-e48076fa47e3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ca773327-cc3f-4922-af32-e48076fa47e3" start_index="0" end="7e23ea22-600f-4263-89af-defa541e90f2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="315c8e1c-c741-40dc-9636-56d19a140896" start_index="0" end="ca773327-cc3f-4922-af32-e48076fa47e3" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="92552ee0-bf78-48ad-9f66-97291b175a48" start_index="0" end="6e9a64fa-8937-4cea-95fc-bd52aaf3404a" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Converting Revit curve to Curve Geometry" x="177.184676917625" y="24.6392233648715" />
    <Dynamo.Models.NoteModel text="Parameter should be 0 to 1 and 'x' is for defining number of Points on Curve" x="152.981784677773" y="264.770036120399" />
    <Dynamo.Models.NoteModel text="Select curve from Revit" x="-63.8933024180454" y="4.6905074041183" />
  </Notes>
</Workspace>