<Workspace Version="0.7.0.21043" X="245.848149707198" Y="191.036942742988" zoom="1.2198072017255" Description="" Category="" Name="Home">
  <Elements>
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="7e23ea22-600f-4263-89af-defa541e90f2" nickname="ReferencePoint.ByPoint" x="616.799136739771" y="101.244013709725" isVisible="true" isUpstreamVisible="true" lacing="Longest" assembly="..\..\RevitNodes.dll" function="Revit.Elements.ReferencePoint.ByPoint@Autodesk.DesignScript.Geometry.Point" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="6e9a64fa-8937-4cea-95fc-bd52aaf3404a" nickname="CurveElement.Curve" x="203.586846097514" y="68.7416719484366" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="..\..\RevitNodes.dll" function="Revit.Elements.CurveElement.Curve" />
    <Dynamo.Nodes.DSFunction type="Dynamo.Nodes.DSFunction" guid="ca773327-cc3f-4922-af32-e48076fa47e3" nickname="Curve.PointAtParameter" x="419.063741936948" y="101.244013709725" isVisible="true" isUpstreamVisible="true" lacing="Shortest" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double" />
    <Dynamo.Nodes.CodeBlockNodeModel type="Dynamo.Nodes.CodeBlockNodeModel" guid="315c8e1c-c741-40dc-9636-56d19a140896" nickname="Code Block" x="233.586846097514" y="182.559968084746" isVisible="true" isUpstreamVisible="true" lacing="Disabled" CodeText="0..1..#10;" ShouldFocus="false" />
    <Dynamo.Nodes.DSModelElementSelection type="Dynamo.Nodes.DSModelElementSelection" guid="92552ee0-bf78-48ad-9f66-97291b175a48" nickname="Select Model Element" x="-66.0907127429806" y="49.903086153108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="6e9a64fa-8937-4cea-95fc-bd52aaf3404a" start_index="0" end="ca773327-cc3f-4922-af32-e48076fa47e3" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ca773327-cc3f-4922-af32-e48076fa47e3" start_index="0" end="7e23ea22-600f-4263-89af-defa541e90f2" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="315c8e1c-c741-40dc-9636-56d19a140896" start_index="0" end="ca773327-cc3f-4922-af32-e48076fa47e3" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="92552ee0-bf78-48ad-9f66-97291b175a48" start_index="0" end="6e9a64fa-8937-4cea-95fc-bd52aaf3404a" end_index="0" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Models.NoteModel text="Converting Revit curve to DS Curve" x="177.184676917625" y="24.6392233648715" />
    <Dynamo.Models.NoteModel text="Paramter should be 0 to 1 and '#10' defines number of Points on Curve" x="145.907410888007" y="258.579959054354" />
    <Dynamo.Models.NoteModel text="Select curve from Revit" x="-66.2431767932392" y="3.38320593452152" />
  </Notes>
</Workspace>